/* Generated by scripts/prepare-plates.mjs; all artwork is local. */
const PLATES = {
  "hero": {
    "src": "assets/plates/hero.png",
    "alt": "佛光寺东大殿柱头铺作 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#d6ab5c",
    "tint": false
  },
  "liyeque": {
    "src": "assets/plates/liyeque.png",
    "alt": "梓潼李业阙现存单阙南面（阙顶为后世补配） · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#b79d77",
    "tint": false,
    "caption": [
      "李业阙 · 现存单阙南面",
      "东汉初年阙身，阙顶为后配"
    ]
  },
  "taishique": {
    "src": "assets/plates/taishique.png",
    "alt": "登封太室阙·西阙南面 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#b79d77",
    "tint": false,
    "caption": [
      "太室阙 · 西阙南面",
      "东汉元初五年"
    ]
  },
  "shaoshique": {
    "src": "assets/plates/shaoshique.png",
    "alt": "登封少室阙·西阙南面 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#b79d77",
    "tint": false,
    "caption": [
      "少室阙 · 西阙南面",
      "东汉子母阙"
    ]
  },
  "qimuque": {
    "src": "assets/plates/qimuque.png",
    "alt": "登封启母阙·西阙南面 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#b79d77",
    "tint": false,
    "caption": [
      "启母阙 · 西阙南面",
      "残存阙顶 · 东汉石刻"
    ]
  },
  "gaoyique": {
    "src": "assets/plates/gaoyique.png",
    "alt": "雅安高颐阙西侧子母阙近正视 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#b79d77",
    "tint": false,
    "caption": [
      "高颐阙 · 西侧子母阙",
      "近正视 · 东汉建安十四年"
    ]
  },
  "sx_yungang": {
    "src": "assets/plates/sx_yungang.png",
    "alt": "云冈第20窟 · 主尊坐像 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#ac8fa6",
    "tint": false,
    "caption": [
      "云冈第20窟 · 主尊坐像",
      "北魏 · 约460—470"
    ]
  },
  "songyue": {
    "src": "assets/plates/songyue.png",
    "alt": "登封嵩岳寺塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#ac8fa6",
    "tint": false,
    "caption": [
      "嵩岳寺塔 · 正面",
      "十二边形 · 十五层密檐"
    ]
  },
  "hn_gongyi": {
    "src": "assets/plates/hn_gongyi.png",
    "alt": "巩县石窟第一窟 · 中心柱主像与胁侍 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#ac8fa6",
    "tint": false,
    "caption": [
      "巩县石窟第一窟 · 中心柱主像与胁侍",
      "北魏晚期 · 石窟造像轮廓"
    ]
  },
  "xinchangdafo": {
    "src": "assets/plates/xinchangdafo.png",
    "alt": "新昌大佛寺历史石弥勒坐像与头光、身光 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#b58d67",
    "tint": false,
    "caption": [
      "新昌大佛寺 · 石弥勒像",
      "南朝齐梁 · 486—516年"
    ]
  },
  "hn_xiaonanhai": {
    "src": "assets/plates/hn_xiaonanhai.png",
    "alt": "小南海石窟 · 窟门崖面局部 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#bf8390",
    "tint": false,
    "caption": [
      "小南海石窟 · 窟门崖面局部",
      "北齐天保年间开凿 · 保留门侧残损雕刻"
    ]
  },
  "xiangtang": {
    "src": "assets/plates/xiangtang.png",
    "alt": "北响堂山第9窟大佛洞中心柱正面（西侧）主尊与火焰背光 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#bf8390",
    "tint": false,
    "caption": [
      "响堂山石窟 · 北响堂大佛洞主尊",
      "北齐 · 约550年代（推定）"
    ]
  },
  "hn_dapishan": {
    "src": "assets/plates/hn_dapishan.png",
    "alt": "大伾山摩崖大佛 · 头部至双膝可见部分 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#bf8390",
    "tint": false,
    "caption": [
      "大伾山摩崖大佛 · 头部至双膝可见部分",
      "开凿年代有争议 · 依2024年实拍现状绘制"
    ]
  },
  "sx_tianlongshan": {
    "src": "assets/plates/sx_tianlongshan.png",
    "alt": "天龙山第16窟 · 石刻前廊 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#bf8390",
    "tint": false,
    "caption": [
      "天龙山第16窟 · 石刻前廊",
      "北齐 · 仿木构局部"
    ]
  },
  "hb_yicihui": {
    "src": "assets/plates/hb_yicihui.png",
    "alt": "义慈惠石柱 · 北齐石柱及柱顶三间石殿 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#bf8390",
    "tint": false,
    "caption": [
      "定兴 · 义慈惠石柱",
      "北齐石构 · 柱顶石殿"
    ]
  },
  "hn_lingquan": {
    "src": "assets/plates/hn_lingquan.png",
    "alt": "灵泉寺大住圣窟 · 门侧成对护法局部 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#90aab6",
    "tint": false,
    "caption": [
      "灵泉寺大住圣窟 · 门侧成对护法局部",
      "隋开皇九年（589） · 迦毗罗与那罗延神王"
    ]
  },
  "hb_anjibridge": {
    "src": "assets/plates/hb_anjibridge.png",
    "alt": "赵州桥（安济桥） · 敞肩石拱桥侧立面 · 线稿",
    "width": 2005,
    "height": 784,
    "color": "#90aab6",
    "tint": false,
    "caption": [
      "赵州桥（安济桥） · 敞肩石拱桥侧立面",
      "隋 · 隋代"
    ]
  },
  "kaiyuan": {
    "src": "assets/plates/kaiyuan.png",
    "alt": "正定开元寺须弥塔与钟楼 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#d6ab5c",
    "tint": false
  },
  "xiuding": {
    "src": "assets/plates/xiuding.png",
    "alt": "修定寺塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#d6ab5c",
    "tint": false
  },
  "xian": {
    "src": "assets/plates/xian.png",
    "alt": "西安大雁塔 · 小雁塔 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#d6ab5c",
    "tint": false
  },
  "hn_fengxue": {
    "src": "assets/plates/hn_fengxue.png",
    "alt": "风穴寺七祖塔 · 西南近正面 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#d6ab5c",
    "tint": false,
    "caption": [
      "风穴寺七祖塔 · 西南近正面",
      "唐开元二十六年（738） · 方形九层密檐砖塔"
    ]
  },
  "hb_daodejing": {
    "src": "assets/plates/hb_daodejing.png",
    "alt": "龙兴观道德经幢 · 幢身与莲座局部 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#d6ab5c",
    "tint": false,
    "caption": [
      "龙兴观道德经幢 · 幢身与莲座局部",
      "唐 · 738"
    ]
  },
  "haichunxuan": {
    "src": "assets/plates/haichunxuan.png",
    "alt": "东台海春轩塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#d6ab5c",
    "tint": false,
    "caption": [
      "海春轩塔 · 七级八角",
      "唐代古塔 · 宋代修葺"
    ]
  },
  "nanchan": {
    "src": "assets/plates/nanchan.png",
    "alt": "南禅寺大殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#d6ab5c",
    "tint": false
  },
  "sx_longshan": {
    "src": "assets/plates/sx_longshan.png",
    "alt": "龙山三天大法师窟 · 主尊局部 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#d6ab5c",
    "tint": false,
    "caption": [
      "龙山三天大法师窟 · 主尊局部",
      "唐代龛像 · 原物残貌"
    ]
  },
  "guangren": {
    "src": "assets/plates/guangren.png",
    "alt": "芮城广仁王庙正殿（龙王殿） · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#d6ab5c",
    "tint": false,
    "caption": [
      "广仁王庙正殿正面 · 据实景照片重绘",
      "唐代木构 · 五间单檐歇山顶，墙面及屋面历经修缮"
    ]
  },
  "longxingchuang": {
    "src": "assets/plates/longxingchuang.png",
    "alt": "杭州龙兴寺经幢 · 唐代幢身局部 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#d6ab5c",
    "tint": false,
    "caption": [
      "龙兴寺经幢 · 幢身局部",
      "唐开成二年 · 837年"
    ]
  },
  "chongsheng": {
    "src": "assets/plates/chongsheng.png",
    "alt": "大理崇圣寺三塔：千寻塔、南塔、北塔 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#d6ab5c",
    "tint": false,
    "caption": [
      "崇圣寺三塔 · 东向组合视图",
      "千寻塔十六层，南北小塔各十层"
    ]
  },
  "foguang": {
    "src": "assets/plates/foguang.png",
    "alt": "佛光寺东大殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#d6ab5c",
    "tint": false
  },
  "sh_tangchuang": {
    "src": "assets/plates/sh_tangchuang.png",
    "alt": "松江唐经幢 · 佛顶尊胜陀罗尼经幢 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#d6ab5c",
    "tint": false,
    "caption": [
      "八角石幢 · 层叠雕刻",
      "唐 · 大中十三年（859）"
    ]
  },
  "gongchen": {
    "src": "assets/plates/gongchen.png",
    "alt": "临安功臣塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#8f8caa",
    "tint": false
  },
  "longmen": {
    "src": "assets/plates/longmen.png",
    "alt": "龙门寺西配殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#8f8caa",
    "tint": false
  },
  "hb_zdwenmiao": {
    "src": "assets/plates/hb_zdwenmiao.png",
    "alt": "正定县文庙大成殿 · 大成殿正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#8f8caa",
    "tint": false,
    "caption": [
      "正定县文庙大成殿 · 大成殿正面",
      "五代 · 晚唐—五代"
    ]
  },
  "tiantai": {
    "src": "assets/plates/tiantai.png",
    "alt": "平顺天台庵 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#8f8caa",
    "tint": false
  },
  "dayun": {
    "src": "assets/plates/dayun.png",
    "alt": "大云院弥陀殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#8f8caa",
    "tint": false
  },
  "fuzhouwuta": {
    "src": "assets/plates/fuzhouwuta.png",
    "alt": "福州乌塔（崇妙保圣坚牢塔） · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#8f8caa",
    "tint": false,
    "caption": [
      "福州乌塔 · 崇妙保圣坚牢塔",
      "七层八角 · 五代石塔"
    ]
  },
  "wenfeng": {
    "src": "assets/plates/wenfeng.png",
    "alt": "安阳文峰塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#8f8caa",
    "tint": false
  },
  "hb_cangzhoulion": {
    "src": "assets/plates/hb_cangzhoulion.png",
    "alt": "沧州铁狮子 · 旧州现存铁狮原物（保留残缺） · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#8f8caa",
    "tint": false,
    "caption": [
      "沧州铁狮原物",
      "依2020年实拍保留残损与保护支架"
    ]
  },
  "zhakoubaita": {
    "src": "assets/plates/zhakoubaita.png",
    "alt": "杭州闸口白塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#8f8caa",
    "tint": false,
    "caption": [
      "闸口白塔",
      "九层仿木石塔 · 五代吴越"
    ]
  },
  "huqiuta": {
    "src": "assets/plates/huqiuta.png",
    "alt": "苏州虎丘云岩寺塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#8f8caa",
    "tint": false,
    "caption": [
      "虎丘 · 云岩寺塔",
      "近正面 · 五代吴越（959—961）"
    ]
  },
  "qixia": {
    "src": "assets/plates/qixia.png",
    "alt": "南京栖霞寺舍利塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#8f8caa",
    "tint": false,
    "caption": [
      "栖霞寺 · 舍利塔",
      "五层石塔 · 南唐重建"
    ]
  },
  "lingyin": {
    "src": "assets/plates/lingyin.png",
    "alt": "灵隐寺石塔与经幢 · 各取一座对照 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#8f8caa",
    "tint": false,
    "caption": [
      "石塔与经幢 · 对照线稿",
      "吴越 · 960 · 969年"
    ]
  },
  "sx_zhenguo": {
    "src": "assets/plates/sx_zhenguo.png",
    "alt": "镇国寺万佛殿 · 正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#8f8caa",
    "tint": false,
    "caption": [
      "镇国寺万佛殿 · 正面",
      "北汉天会七年 · 963"
    ]
  },
  "hualin": {
    "src": "assets/plates/hualin.png",
    "alt": "福州华林寺大殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "华林寺大殿线稿 · 面阔三间",
      "单檐歇山 · 北宋乾德二年"
    ]
  },
  "chongming": {
    "src": "assets/plates/chongming.png",
    "alt": "高平崇明寺中佛殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "中佛殿线稿 · 面阔三间",
      "七铺作 · 单檐歇山 · 北宋"
    ]
  },
  "longxing": {
    "src": "assets/plates/longxing.png",
    "alt": "正定隆兴寺摩尼殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false
  },
  "hn_jidu": {
    "src": "assets/plates/hn_jidu.png",
    "alt": "济渎庙寝宫 · 正立面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "济渎庙寝宫 · 正立面",
      "北宋开宝六年（973） · 面阔五间歇山顶"
    ]
  },
  "hn_fanta": {
    "src": "assets/plates/hn_fanta.png",
    "alt": "开封繁塔 · 现存三层主体与小塔 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "开封繁塔 · 现存三层主体与小塔",
      "宋 · 974 · 后世修补"
    ]
  },
  "sh_longhuata": {
    "src": "assets/plates/sh_longhuata.png",
    "alt": "龙华塔 · 八面七层 · 砖木楼阁塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "八面七层 · 砖木楼阁式",
      "吴越重建 · 北宋纪年（977）"
    ]
  },
  "luohanshuangta": {
    "src": "assets/plates/luohanshuangta.png",
    "alt": "苏州罗汉院双塔与正殿石柱遗迹 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "罗汉院双塔 · 石柱遗迹",
      "北宋 · 太平兴国七年始建"
    ]
  },
  "sx_youxian": {
    "src": "assets/plates/sx_youxian.png",
    "alt": "高平游仙寺毗卢殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "游仙寺 · 毗卢殿",
      "北宋淳化时期 · 约990—994"
    ]
  },
  "songyangyanqing": {
    "src": "assets/plates/songyangyanqing.png",
    "alt": "松阳延庆寺塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "松阳 · 延庆寺塔",
      "六面七级 · 底层副阶重檐"
    ]
  },
  "yuanqi": {
    "src": "assets/plates/yuanqi.png",
    "alt": "原起寺青龙塔与大雄宝殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false
  },
  "ruiguang": {
    "src": "assets/plates/ruiguang.png",
    "alt": "苏州瑞光塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "瑞光塔 · 七级八面",
      "北宋塔身 · 木檐后修"
    ]
  },
  "baoguo": {
    "src": "assets/plates/baoguo.png",
    "alt": "宁波保国寺大殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false
  },
  "sx_chongqing": {
    "src": "assets/plates/sx_chongqing.png",
    "alt": "长子崇庆寺千佛殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "崇庆寺 · 千佛殿",
      "北宋大中祥符九年 · 1016"
    ]
  },
  "hb_xiude": {
    "src": "assets/plates/hb_xiude.png",
    "alt": "修德寺塔 · 现存楼阁与花塔混合式砖塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "曲阳 · 修德寺塔",
      "现状塔身 · 楼阁与花塔合构"
    ]
  },
  "jiwang": {
    "src": "assets/plates/jiwang.png",
    "alt": "万荣稷王庙正殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "万荣稷王庙 · 正殿",
      "五间庑殿 · 北宋遗构"
    ]
  },
  "haiqing": {
    "src": "assets/plates/haiqing.png",
    "alt": "连云港海清寺阿育王塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "海清寺 · 阿育王塔",
      "八面九级砖塔 · 北宋天圣元年重建"
    ]
  },
  "hb_tuoluoni": {
    "src": "assets/plates/hb_tuoluoni.png",
    "alt": "赵州陀罗尼经幢 · 七级石经幢 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "赵州陀罗尼经幢 · 七级石经幢",
      "宋 · 1038"
    ]
  },
  "lingxiao": {
    "src": "assets/plates/lingxiao.png",
    "alt": "正定天宁寺凌霄塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false
  },
  "hn_tieta": {
    "src": "assets/plates/hn_tieta.png",
    "alt": "开封铁塔 · 祐国寺琉璃塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "开封铁塔 · 祐国寺琉璃塔",
      "宋 · 1049"
    ]
  },
  "fotou": {
    "src": "assets/plates/fotou.png",
    "alt": "平顺佛头寺 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "佛殿线稿 · 面阔三间",
      "单檐歇山 · 现存金构"
    ]
  },
  "baosheng": {
    "src": "assets/plates/baosheng.png",
    "alt": "甪直保圣寺罗汉塑像单尊与相邻山石塑壁局部 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "保圣寺 · 罗汉塑像与山石塑壁（局部）",
      "北宋 · 后世修补"
    ]
  },
  "hb_puli": {
    "src": "assets/plates/hb_puli.png",
    "alt": "普利寺塔 · 方形七层砖塔与高石台基 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "临城普利寺塔",
      "方形七层塔身与平坐檐；不绘外围高台全貌"
    ]
  },
  "liaodi": {
    "src": "assets/plates/liaodi.png",
    "alt": "定州开元寺料敌塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false
  },
  "sd_pizhi": {
    "src": "assets/plates/sd_pizhi.png",
    "alt": "济南灵岩寺辟支塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "八角九层 · 下三层重檐",
      "北宋重建 · 现存砖塔"
    ]
  },
  "hn_xiangshan": {
    "src": "assets/plates/hn_xiangshan.png",
    "alt": "香山寺大悲观音大士塔 · 现状可见塔身 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "香山寺大悲观音大士塔 · 现状可见塔身",
      "北宋熙宁元年重建 · 下部遮挡处留白"
    ]
  },
  "sx_kaihua": {
    "src": "assets/plates/sx_kaihua.png",
    "alt": "高平开化寺大雄宝殿 · 线稿",
    "width": 1518,
    "height": 1036,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "开化寺 · 大雄宝殿",
      "北宋熙宁六年 · 1073"
    ]
  },
  "hb_jingzhouta": {
    "src": "assets/plates/hb_jingzhouta.png",
    "alt": "开福寺舍利塔 · 八角十三层楼阁式塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "景州塔正面",
      "十三层八角塔身与铁刹网、铜葫芦"
    ]
  },
  "sh_fangta": {
    "src": "assets/plates/sh_fangta.png",
    "alt": "松江兴圣教寺塔 · 方塔园 · 九层方塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "方形九层 · 砖木塔",
      "北宋 · 熙宁、元祐年间"
    ]
  },
  "qinglian": {
    "src": "assets/plates/qinglian.png",
    "alt": "晋城青莲寺上寺释迦殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "上寺释迦殿线稿 · 面阔三间",
      "单檐歇山 · 北宋元祐四年"
    ]
  },
  "sx_wubian": {
    "src": "assets/plates/sx_wubian.png",
    "alt": "太谷无边寺白塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "无边寺 · 白塔",
      "北宋元祐五年 · 八角楼阁塔"
    ]
  },
  "hn_chongfa": {
    "src": "assets/plates/hn_chongfa.png",
    "alt": "崇法寺塔 · 近正面 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "崇法寺塔 · 近正面",
      "北宋绍圣五年（1098）竣工 · 八角九层楼阁式砖塔"
    ]
  },
  "anyue": {
    "src": "assets/plates/anyue.png",
    "alt": "安岳毗卢洞水月观音（紫竹观音） · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "安岳石刻 · 毗卢洞水月观音",
      "宋代 · 紫竹观音游戏坐"
    ]
  },
  "hn_xiaoshang": {
    "src": "assets/plates/hn_xiaoshang.png",
    "alt": "小商桥 · 石拱桥侧立面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "小商桥 · 石拱桥侧立面",
      "宋代主体、历代修缮 · 一主拱与左右各一腹拱"
    ]
  },
  "jinci": {
    "src": "assets/plates/jinci.png",
    "alt": "晋祠圣母殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "晋祠 · 圣母殿",
      "北宋 · 七间重檐与八根盘龙柱"
    ]
  },
  "sx_faxing": {
    "src": "assets/plates/sx_faxing.png",
    "alt": "山西长子法兴寺圆觉殿中央释迦牟尼坐像及莲座、台座 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "法兴寺圆觉殿 · 释迦牟尼坐像",
      "北宋政和元年（1111）宋塑 · 随寺迁建现状"
    ]
  },
  "hn_chuzu": {
    "src": "assets/plates/hn_chuzu.png",
    "alt": "少林寺初祖庵 · 初祖庵大殿正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "少林寺初祖庵 · 初祖庵大殿正面",
      "宋 · 1125"
    ]
  },
  "liuhe": {
    "src": "assets/plates/liuhe.png",
    "alt": "杭州六和塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false
  },
  "xuanmiao": {
    "src": "assets/plates/xuanmiao.png",
    "alt": "苏州玄妙观三清殿（非山门） · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "玄妙观 · 三清殿正面",
      "南宋淳熙六年（1179） · 九间重檐歇山"
    ]
  },
  "dazu": {
    "src": "assets/plates/dazu.png",
    "alt": "大足宝顶山第8号龛千手观音主尊 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "大足石刻 · 宝顶山千手观音",
      "南宋 · 主尊与放射手臂局部"
    ]
  },
  "feilaifeng": {
    "src": "assets/plates/feilaifeng.png",
    "alt": "杭州飞来峰第68龛布袋弥勒及邻近四尊罗汉（局部） · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "飞来峰第68龛 · 布袋弥勒与邻近罗汉（局部）",
      "南宋（传统断代，亦有元初说）"
    ]
  },
  "zijinan": {
    "src": "assets/plates/zijinan.png",
    "alt": "苏州东山紫金庵第十尊者半托迦罗汉塑像上身局部 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "紫金庵 · 半托迦尊者（上身局部）",
      "宋—明 · 历代修护"
    ]
  },
  "feiying": {
    "src": "assets/plates/feiying.png",
    "alt": "湖州飞英塔外塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "飞英塔 · 外塔",
      "完整外立面 · 南宋重建"
    ]
  },
  "baziqiao": {
    "src": "assets/plates/baziqiao.png",
    "alt": "绍兴八字桥南侧近正面石梁桥与两岸石阶 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "八字桥 · 南侧石梁桥与沿河石阶",
      "南宋 · 宝祐四年（1256）重建"
    ]
  },
  "geyuan": {
    "src": "assets/plates/geyuan.png",
    "alt": "涞源阁院寺文殊殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "阁院寺文殊殿线稿 · 面阔三间",
      "单檐歇山 · 辽代木构"
    ]
  },
  "dule": {
    "src": "assets/plates/dule.png",
    "alt": "天津独乐寺观音阁 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "独乐寺观音阁正面 · 据实景照片重绘",
      "辽统和二年（984）重建 · 面阔五间，外观两层、内部三层"
    ]
  },
  "kaishan": {
    "src": "assets/plates/kaishan.png",
    "alt": "高碑店开善寺大雄宝殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false
  },
  "fengguo": {
    "src": "assets/plates/fengguo.png",
    "alt": "义县奉国寺大雄殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "奉国寺大雄殿线稿 · 面阔九间",
      "单檐庑殿 · 辽开泰九年"
    ]
  },
  "zhuozhou": {
    "src": "assets/plates/zhuozhou.png",
    "alt": "涿州双塔（云居寺塔与智度寺塔） · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "云居寺塔 · 智度寺塔",
      "北塔六层 · 南塔五层"
    ]
  },
  "huayan": {
    "src": "assets/plates/huayan.png",
    "alt": "大同华严寺大雄宝殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false
  },
  "qingzhou": {
    "src": "assets/plates/qingzhou.png",
    "alt": "辽庆州白塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "辽庆州白塔",
      "八角七级，北立面"
    ]
  },
  "huanghuatan": {
    "src": "assets/plates/huanghuatan.png",
    "alt": "辽宁朝阳黄花滩塔·东南券门面 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "黄花滩塔 · 辽宁朝阳",
      "十三层密檐 · 修缮后现貌"
    ]
  },
  "yingxian": {
    "src": "assets/plates/yingxian.png",
    "alt": "应县木塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#c8442b",
    "tint": false
  },
  "hb_nanansi": {
    "src": "assets/plates/hb_nanansi.png",
    "alt": "南安寺塔 · 十三层密檐砖塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "蔚县南安寺塔",
      "八角十三层密檐塔与仰莲塔座"
    ]
  },
  "tianning": {
    "src": "assets/plates/tianning.png",
    "alt": "北京天宁寺塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#c8442b",
    "tint": false
  },
  "huilong": {
    "src": "assets/plates/huilong.png",
    "alt": "平顺侯壁村回龙寺正殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "正殿线稿 · 面阔三间",
      "单檐悬山 · 宋金之际"
    ]
  },
  "shanhua": {
    "src": "assets/plates/shanhua.png",
    "alt": "大同善化寺普贤阁 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false
  },
  "sx_xixi_erxian": {
    "src": "assets/plates/sx_xixi_erxian.png",
    "alt": "陵川西溪二仙庙后殿（正殿） · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "西溪二仙庙 · 后殿",
      "金代 · 1142年起重建"
    ]
  },
  "sx_chongfu": {
    "src": "assets/plates/sx_chongfu.png",
    "alt": "崇福寺弥陀殿 · 正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "崇福寺弥陀殿 · 正面",
      "七间单檐歇山 · 金"
    ]
  },
  "sx_macun": {
    "src": "assets/plates/sx_macun.png",
    "alt": "马村一号墓妇人启门砖雕壁面局部 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "马村砖雕墓 · 一号墓妇人启门",
      "金代 · 墓室砖雕局部线描"
    ]
  },
  "yuanjue": {
    "src": "assets/plates/yuanjue.png",
    "alt": "浑源圆觉寺塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "圆觉寺塔线稿 · 八角九级",
      "密檐式砖塔 · 金正隆三年"
    ]
  },
  "chunhua": {
    "src": "assets/plates/chunhua.png",
    "alt": "平顺淳化寺正殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false
  },
  "huata": {
    "src": "assets/plates/huata.png",
    "alt": "正定广惠寺华塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#c8442b",
    "tint": false
  },
  "sx_pingyaowenmiao": {
    "src": "assets/plates/sx_pingyaowenmiao.png",
    "alt": "平遥文庙 · 大成殿正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "平遥文庙 · 大成殿正面",
      "金 · 1163"
    ]
  },
  "yanshan": {
    "src": "assets/plates/yanshan.png",
    "alt": "繁峙岩山寺文殊殿（南殿） · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "岩山寺文殊殿正面 · 据实景照片重绘",
      "金代遗构，元延祐二年（1315）重修 · 五间单檐歇山顶"
    ]
  },
  "hn_baima": {
    "src": "assets/plates/hn_baima.png",
    "alt": "白马寺齐云塔 · 方形十三层密檐塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "白马寺齐云塔 · 方形十三层密檐塔",
      "金大定十五年（1175）重建"
    ]
  },
  "hn_baolun": {
    "src": "assets/plates/hn_baolun.png",
    "alt": "宝轮寺塔 · 南立面 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "宝轮寺塔 · 南立面",
      "金大定十七年（1177） · 方形十三层密檐砖塔"
    ]
  },
  "wangbao": {
    "src": "assets/plates/wangbao.png",
    "alt": "高平王报二郎庙金代戏台正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "王报二郎庙 · 金代戏台",
      "金 · 大定二十三年（1183）"
    ]
  },
  "jingtusi": {
    "src": "assets/plates/jingtusi.png",
    "alt": "应县净土寺大雄宝殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "净土寺大雄宝殿正面 · 据实景照片重绘",
      "金大定二十四年重修（1184）· 三间单檐歇山顶"
    ]
  },
  "hn_fengxian": {
    "src": "assets/plates/hn_fengxian.png",
    "alt": "奉仙观三清殿 · 五间悬山大殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "奉仙观三清殿 · 五间悬山大殿",
      "金大定二十四年（1184）"
    ]
  },
  "hb_linji": {
    "src": "assets/plates/hb_linji.png",
    "alt": "临济寺澄灵塔 · 八角九级密檐塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "临济寺澄灵塔 · 八角九级密檐塔",
      "金 · 1185大修"
    ]
  },
  "hongfu": {
    "src": "assets/plates/hongfu.png",
    "alt": "定襄洪福寺大雄宝殿（毗卢殿） · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "洪福寺大雄宝殿正面 · 据实景照片重绘",
      "金代遗构 · 面阔五间，单檐悬山顶"
    ]
  },
  "yanqing": {
    "src": "assets/plates/yanqing.png",
    "alt": "五台善文村延庆寺大佛殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "延庆寺大佛殿正面 · 五台善文村",
      "金代遗构 · 三间歇山顶，现状保留后世柱头兽面"
    ]
  },
  "sx_taifu": {
    "src": "assets/plates/sx_taifu.png",
    "alt": "汾阳太符观昊天玉皇上帝殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "太符观 · 昊天玉皇上帝殿",
      "金代 · 三间单檐歇山"
    ]
  },
  "yongle": {
    "src": "assets/plates/yongle.png",
    "alt": "芮城永乐宫三清殿（无极殿） · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "永乐宫 · 三清殿正面",
      "七间庑殿 · 中统三年"
    ]
  },
  "hn_guanxing": {
    "src": "assets/plates/hn_guanxing.png",
    "alt": "登封观星台 · 台体与石圭正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "登封观星台 · 台体与石圭正面",
      "元 · 1276"
    ]
  },
  "fenghuangsi": {
    "src": "assets/plates/fenghuangsi.png",
    "alt": "杭州凤凰寺元代核心礼拜殿（后窑殿）屋顶群与可见上部 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "凤凰寺礼拜殿 · 实景可见屋顶群",
      "元代核心殿，历代修缮 · 三攒尖顶与上部墙身"
    ]
  },
  "sx_jishi": {
    "src": "assets/plates/sx_jishi.png",
    "alt": "高平姬氏民居元代正房 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "姬氏民居 · 三间元代正房",
      "至元三十一年 · 1294"
    ]
  },
  "hn_yuzhoutianning": {
    "src": "assets/plates/hn_yuzhoutianning.png",
    "alt": "禹州天宁万寿寺大殿 · 现状近正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "禹州天宁万寿寺大殿 · 现状近正面",
      "元大德三年（1299）重建 · 三间单檐歇山顶"
    ]
  },
  "jiutian": {
    "src": "assets/plates/jiutian.png",
    "alt": "九天圣母庙献殿 · 长边侧立面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "献殿线稿 · 侧立面 · 进深五间",
      "庑殿顶 · 正脊沿进深 · 元"
    ]
  },
  "hn_huishan": {
    "src": "assets/plates/hn_huishan.png",
    "alt": "登封会善寺 · 元代大殿正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "登封会善寺 · 元代大殿正面",
      "元 · 元代"
    ]
  },
  "hb_shijia": {
    "src": "assets/plates/hb_shijia.png",
    "alt": "释迦寺 · 三间单檐歇山大雄宝殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "释迦寺中殿",
      "元代三间单檐歇山大雄宝殿正面"
    ]
  },
  "sx_jiangzhou_datang": {
    "src": "assets/plates/sx_jiangzhou_datang.png",
    "alt": "绛州大堂元代正堂南立面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "绛州大堂 · 州署正堂",
      "元代 · 七间悬山"
    ]
  },
  "sx_fusheng": {
    "src": "assets/plates/sx_fusheng.png",
    "alt": "新绛福胜寺弥陀殿北立面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "福胜寺 · 弥陀殿北立面",
      "元代遗构 · 明代修缮"
    ]
  },
  "sx_zezhou_yuhuang": {
    "src": "assets/plates/sx_zezhou_yuhuang.png",
    "alt": "府城玉皇庙二十八宿彩塑之虚日鼠 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "泽州玉皇庙 · 虚日鼠",
      "元代 · 二十八宿代表彩塑"
    ]
  },
  "hb_ciyunge": {
    "src": "assets/plates/hb_ciyunge.png",
    "alt": "慈云阁 · 现存两层三间楼阁 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "定兴 · 慈云阁",
      "两层三间 · 元大德十年重建"
    ]
  },
  "yongan": {
    "src": "assets/plates/yongan.png",
    "alt": "浑源永安禅寺传法正宗殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "传法正宗殿线稿 · 面阔五间",
      "单檐庑殿 · 元延祐二年"
    ]
  },
  "yanfu": {
    "src": "assets/plates/yanfu.png",
    "alt": "武义延福寺大殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "延福寺 · 大殿",
      "元延祐四年 · 重檐歇山"
    ]
  },
  "jinhuatianning": {
    "src": "assets/plates/jinhuatianning.png",
    "alt": "金华天宁寺大殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "金华天宁寺 · 大殿",
      "元延祐五年 · 单檐歇山"
    ]
  },
  "sh_zhenru": {
    "src": "assets/plates/sh_zhenru.png",
    "alt": "真如寺大殿 · 三间单檐歇山 · 元代木构 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "大殿正立面 · 面阔三间",
      "元 · 延祐七年（1320）"
    ]
  },
  "xiayu": {
    "src": "assets/plates/xiayu.png",
    "alt": "夏禹神祠正殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false
  },
  "duanliang": {
    "src": "assets/plates/duanliang.png",
    "alt": "苏州虎丘云岩寺二山门（断梁殿） · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "虎丘二山门 · 断梁殿正面",
      "元至元四年（1338）重建 · 三间单檐歇山"
    ]
  },
  "hb_beiyue": {
    "src": "assets/plates/hb_beiyue.png",
    "alt": "北岳庙 · 德宁之殿正立面（含回廊、台基） · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "曲阳 · 北岳庙德宁之殿",
      "元代木构 · 重檐庑殿"
    ]
  },
  "xuanyuan": {
    "src": "assets/plates/xuanyuan.png",
    "alt": "苏州东山杨湾轩辕宫正殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "东山杨湾 · 轩辕宫正殿",
      "三间单檐歇山 · 元代特征与明清修建并存"
    ]
  },
  "shisi": {
    "src": "assets/plates/shisi.png",
    "alt": "景宁时思寺大殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "时思寺 · 大殿",
      "元至正十六年 · 重檐歇山"
    ]
  },
  "jijian": {
    "src": "assets/plates/jijian.png",
    "alt": "苏州天池山寂鉴寺西天寺石殿（1357） · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "寂鉴寺 · 西天寺石殿正面",
      "元至正十七年（1357） · 三间石构仿木"
    ]
  },
  "sx_jishan_qinglong": {
    "src": "assets/plates/sx_jishan_qinglong.png",
    "alt": "稷山青龙寺腰殿西壁三世佛壁画局部 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "青龙寺 · 腰殿西壁三世佛局部",
      "元末—明初 · 壁画线描转绘"
    ]
  },
  "sx_pingyaowall": {
    "src": "assets/plates/sx_pingyaowall.png",
    "alt": "平遥城墙 · 迎薰门及相邻墙段 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "平遥城墙 · 迎薰门及相邻墙段",
      "明清 · 明清"
    ]
  },
  "yuhuang": {
    "src": "assets/plates/yuhuang.png",
    "alt": "蔚州玉皇阁 · 线稿",
    "width": 1584,
    "height": 993,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "蔚州玉皇阁 · 正面",
      "三檐两层 · 面阔五间"
    ]
  },
  "xianwall": {
    "src": "assets/plates/xianwall.png",
    "alt": "西安城墙安定门箭楼西立面及中央单券门洞墙段 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "西安城墙 · 安定门箭楼与中央券洞",
      "明代城垣 · 明清及近现代修葺"
    ]
  },
  "xianzhonggu": {
    "src": "assets/plates/xianzhonggu.png",
    "alt": "西安钟楼与鼓楼并置合绘（左钟楼、右鼓楼） · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "西安钟楼 · 鼓楼",
      "双主体组合图，并非实景相邻"
    ]
  },
  "linggu": {
    "src": "assets/plates/linggu.png",
    "alt": "南京灵谷寺无梁殿单体正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "灵谷寺无梁殿 · 砖券大殿正面",
      "明代遗构 · 重檐九脊与三塔脊饰"
    ]
  },
  "sx_chongshan": {
    "src": "assets/plates/sx_chongshan.png",
    "alt": "太原崇善寺大悲殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "崇善寺 · 大悲殿",
      "明洪武 · 七间重檐庑殿"
    ]
  },
  "shuanglin": {
    "src": "assets/plates/shuanglin.png",
    "alt": "平遥双林寺天王殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false
  },
  "tiantan": {
    "src": "assets/plates/tiantan.png",
    "alt": "北京天坛祈年殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false
  },
  "hb_jimingyi": {
    "src": "assets/plates/hb_jimingyi.png",
    "alt": "鸡鸣驿城 · 东门城台与两翼古城墙 · 线稿",
    "width": 1448,
    "height": 1086,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "怀来鸡鸣驿城 · 东门",
      "门台与两翼墙段；城楼为修复现状"
    ]
  },
  "baoen": {
    "src": "assets/plates/baoen.png",
    "alt": "南京大报恩寺旧琉璃塔（据1915年土山湾模型绘制） · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "九层八面 · 据土山湾旧塔模型绘制",
      "原塔已毁 · 非现代玻璃新塔"
    ]
  },
  "hunyuanwenmiao": {
    "src": "assets/plates/hunyuanwenmiao.png",
    "alt": "浑源文庙大成殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "文庙大成殿线稿 · 面阔五间",
      "单檐庑殿 · 现存明代遗构"
    ]
  },
  "hb_xuanhuaqingyuan": {
    "src": "assets/plates/hb_xuanhuaqingyuan.png",
    "alt": "宣化清远楼 · 十字歇山三重檐钟楼及砖台 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "清远楼南面",
      "三重檐十字歇山顶与砖台券洞"
    ]
  },
  "sx_yuci_chenghuang": {
    "src": "assets/plates/sx_yuci_chenghuang.png",
    "alt": "榆次城隍庙玄鉴楼北侧乐楼与戏台组合 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "榆次城隍庙 · 玄鉴楼北侧",
      "明代 · 乐楼与过路戏台"
    ]
  },
  "zhaoling": {
    "src": "assets/plates/zhaoling.png",
    "alt": "福建仙游顶东湖村东湖昭灵宫现存单殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "仙游昭灵宫 · 单殿正面",
      "明代（待考） · 单檐歇山"
    ]
  },
  "gongzhu": {
    "src": "assets/plates/gongzhu.png",
    "alt": "繁峙公主寺大雄宝殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "公主寺大雄宝殿正面 · 据实景照片重绘",
      "明弘治十六年（1503）重修 · 三间单檐悬山顶，檐下无斗栱"
    ]
  },
  "hb_xtkaiyuan": {
    "src": "assets/plates/hb_xtkaiyuan.png",
    "alt": "邢台开元寺 · 古开元寺菩萨殿（第三殿/释迦牟尼殿），完整正面及四根滚龙石柱 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "邢台开元寺 · 菩萨殿",
      "五间硬山殿与四根滚龙石柱正面"
    ]
  },
  "sx_jiexiu_houtu": {
    "src": "assets/plates/sx_jiexiu_houtu.png",
    "alt": "介休后土庙三清楼北面戏台与八字影壁 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "介休后土庙 · 三清楼北面戏台",
      "明清 · 戏台与八字影壁"
    ]
  },
  "tiefo": {
    "src": "assets/plates/tiefo.png",
    "alt": "高平铁佛寺正殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "正殿线稿 · 面阔三间",
      "单檐悬山 · 明代"
    ]
  },
  "feihong": {
    "src": "assets/plates/feihong.png",
    "alt": "广胜寺飞虹塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7290bd",
    "tint": false
  },
  "taimiao": {
    "src": "assets/plates/taimiao.png",
    "alt": "北京太庙享殿（前殿） · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "北京太庙 · 享殿",
      "十一间面阔 · 三层须弥座"
    ]
  },
  "fuzhoubaita": {
    "src": "assets/plates/fuzhoubaita.png",
    "alt": "福州白塔（报恩定光多宝塔） · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "福州白塔 · 定光塔",
      "七层八角 · 明代重建"
    ]
  },
  "sx_haihui": {
    "src": "assets/plates/sx_haihui.png",
    "alt": "阳城海会寺小砖塔与明代琉璃大塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "海会寺 · 小砖塔与琉璃大塔",
      "五代—宋小塔 · 明嘉靖至隆庆大塔"
    ]
  },
  "guanyintang": {
    "src": "assets/plates/guanyintang.png",
    "alt": "长治观音堂观音主像及天宫悬塑局部 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "长治观音堂 · 观音与天宫悬塑局部",
      "明万历年间 · 彩塑与悬塑"
    ]
  },
  "xuankong": {
    "src": "assets/plates/xuankong.png",
    "alt": "浑源悬空寺现存明清崖壁建筑群 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "悬空寺 · 崖壁建筑群",
      "明清遗构 · 南北楼与凌空栈道"
    ]
  },
  "hn_bigan": {
    "src": "assets/plates/hn_bigan.png",
    "alt": "比干庙享殿 · 前部可见立面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "比干庙享殿 · 前部可见立面",
      "明清重建、续修 · 依据2024年正面实拍"
    ]
  },
  "hb_wahuang": {
    "src": "assets/plates/hb_wahuang.png",
    "alt": "娲皇宫及石刻 · 悬崖前娲皇阁及承托石券 · 线稿",
    "width": 1448,
    "height": 1086,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "涉县娲皇宫 · 娲皇阁",
      "三层木阁与下层前廊的四道檐线"
    ]
  },
  "sx_yongzuo": {
    "src": "assets/plates/sx_yongzuo.png",
    "alt": "太原永祚寺双塔 · 文峰塔与宣文塔 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "太原永祚寺双塔 · 文峰塔与宣文塔",
      "明 · 明万历"
    ]
  },
  "hn_luwang": {
    "src": "assets/plates/hn_luwang.png",
    "alt": "潞简王墓 · 潞藩佳城石坊 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "潞简王墓 · 潞藩佳城石坊",
      "明万历时期 · 三门石坊与双石柱"
    ]
  },
  "rulong": {
    "src": "assets/plates/rulong.png",
    "alt": "庆元月山如龙桥完整侧立面、木拱下缘与桥头钟楼 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "如龙桥 · 木拱桥廊与桥头楼阁",
      "明 · 天启五年（1625）修造"
    ]
  },
  "quanzhoukaiyuan": {
    "src": "assets/plates/quanzhoukaiyuan.png",
    "alt": "泉州开元寺大雄宝殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "泉州开元寺 · 大雄宝殿",
      "明崇祯十年重修 · 九间百柱殿"
    ]
  },
  "xiaoxitian": {
    "src": "assets/plates/xiaoxitian.png",
    "alt": "隰县小西天大雄宝殿中央主龛、悬塑楼阁与群像局部 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "小西天 · 大雄宝殿悬塑局部",
      "明末清初 · 主龛与天宫楼阁"
    ]
  },
  "xianshen": {
    "src": "assets/plates/xianshen.png",
    "alt": "介休祆神楼过街楼与乐楼组合近正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "介休祆神楼 · 过街楼与乐楼",
      "清 · 顺治末至康熙初重建"
    ]
  },
  "hb_qingdongling": {
    "src": "assets/plates/hb_qingdongling.png",
    "alt": "清东陵 · 孝陵神道石牌坊 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "清东陵 · 孝陵石牌坊",
      "五间六柱十一楼正立面"
    ]
  },
  "daimiao": {
    "src": "assets/plates/daimiao.png",
    "alt": "泰安岱庙天贶殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "岱庙天贶殿正面 · 九间重檐庑殿",
      "宋代创建 · 现存清代重修形制"
    ]
  },
  "gugong": {
    "src": "assets/plates/gugong.png",
    "alt": "北京故宫太和殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "故宫 · 太和殿",
      "十一间面阔 · 重檐庑殿顶"
    ]
  },
  "mimi": {
    "src": "assets/plates/mimi.png",
    "alt": "繁峙秘密寺文殊殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "秘密寺 · 文殊殿正面",
      "五间硬山 · 清代遗构"
    ]
  },
  "hn_kangbaiwan": {
    "src": "assets/plates/hn_kangbaiwan.png",
    "alt": "康百万庄园 · 窑楼与内院局部 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "康百万庄园 · 窑楼与内院局部",
      "明清宅院遗构 · 依实景保留楼窑组合"
    ]
  },
  "hn_wuhou": {
    "src": "assets/plates/hn_wuhou.png",
    "alt": "南阳武侯祠 · 大拜殿檐下局部 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "南阳武侯祠 · 大拜殿檐下局部",
      "清代遗构、历代修缮 · 柱梁与门扇空间"
    ]
  },
  "sx_jiezhou_guandi": {
    "src": "assets/plates/sx_jiezhou_guandi.png",
    "alt": "解州关帝庙崇宁殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "解州关帝庙 · 崇宁殿",
      "清代 · 七间重檐大殿"
    ]
  },
  "qufukongmiao": {
    "src": "assets/plates/qufukongmiao.png",
    "alt": "曲阜孔庙大成殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "曲阜孔庙大成殿正面 · 据实景照片重绘",
      "清雍正八年（1730）重建竣工 · 九间重檐歇山顶"
    ]
  },
  "hn_zkguandi": {
    "src": "assets/plates/hn_zkguandi.png",
    "alt": "周口关帝庙 · 山门正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "周口关帝庙 · 山门正面",
      "清雍正十三年 · 五间单檐歇山顶"
    ]
  },
  "hb_qingxiling": {
    "src": "assets/plates/hb_qingxiling.png",
    "alt": "清西陵 · 泰陵隆恩殿正立面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "清西陵 · 泰陵隆恩殿",
      "五间重檐歇山殿与完整石台基"
    ]
  },
  "feiyun": {
    "src": "assets/plates/feiyun.png",
    "alt": "万荣东岳庙飞云楼·南立面 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "东岳庙 · 飞云楼",
      "三层四滴水 · 南立面"
    ]
  },
  "hn_zhongyue": {
    "src": "assets/plates/hn_zhongyue.png",
    "alt": "嵩山中岳庙 · 峻极殿中央立面局部 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "嵩山中岳庙 · 峻极殿中央立面局部",
      "清 · 清代"
    ]
  },
  "sx_jiexiu_chenghuang": {
    "src": "assets/plates/sx_jiexiu_chenghuang.png",
    "alt": "介休城隍庙前殿倒座戏台 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "介休城隍庙 · 倒座戏台",
      "清代 · 历次修复"
    ]
  },
  "hb_bishushanzhuang": {
    "src": "assets/plates/hb_bishushanzhuang.png",
    "alt": "承德避暑山庄 · 澹泊敬诚殿正立面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "承德避暑山庄 · 澹泊敬诚殿",
      "七间单檐卷棚歇山楠木殿正面"
    ]
  },
  "hb_puning": {
    "src": "assets/plates/hb_puning.png",
    "alt": "普宁寺 · 大乘阁完整立面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "普宁寺大乘阁",
      "六重檐高阁及正面石台阶"
    ]
  },
  "sx_dingcun": {
    "src": "assets/plates/sx_dingcun.png",
    "alt": "丁村民居丁坤大院院内厅堂与厢房片段 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "丁村民居 · 丁坤大院院内厅堂",
      "清乾隆时期 · 庭院视角"
    ]
  },
  "quanzhouwenmiao": {
    "src": "assets/plates/quanzhouwenmiao.png",
    "alt": "泉州府文庙大成殿 · 线稿",
    "width": 1678,
    "height": 937,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "泉州府文庙 · 大成殿",
      "清乾隆二十六年 · 保留宋式重檐庑殿"
    ]
  },
  "hb_putuozongcheng": {
    "src": "assets/plates/hb_putuozongcheng.png",
    "alt": "普陀宗乘之庙 · 大红台完整正面及上部实存屋顶 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "普陀宗乘之庙大红台",
      "南侧大红台及紧邻白台的外观"
    ]
  },
  "hn_kfhuiguan": {
    "src": "assets/plates/hn_kfhuiguan.png",
    "alt": "开封山陕甘会馆 · 木牌楼正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "开封山陕甘会馆 · 木牌楼正面",
      "清 · 清代"
    ]
  },
  "sx_xinjiang_longxing": {
    "src": "assets/plates/sx_xinjiang_longxing.png",
    "alt": "新绛龙兴寺塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "新绛龙兴寺 · 龙兴宝塔",
      "清乾隆重修 · 八角十三级"
    ]
  },
  "hn_guanlin": {
    "src": "assets/plates/hn_guanlin.png",
    "alt": "洛阳关林 · 千秋鉴舞楼正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "洛阳关林 · 千秋鉴舞楼正面",
      "清乾隆五十六年 · 前歇山与后硬山组合"
    ]
  },
  "hn_shedian": {
    "src": "assets/plates/hn_shedian.png",
    "alt": "赊店山陕会馆 · 悬鉴楼戏台正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "赊店山陕会馆 · 悬鉴楼戏台正面",
      "清嘉庆至道光时期 · 三重檐楼阁"
    ]
  },
  "hb_jingjue": {
    "src": "assets/plates/hb_jingjue.png",
    "alt": "净觉寺 · 现存清代正殿正立面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "玉田净觉寺 · 香阜宫",
      "正殿与前出卷棚抱厦正面"
    ]
  },
  "hb_dzgongyuan": {
    "src": "assets/plates/hb_dzgongyuan.png",
    "alt": "定州贡院 · 魁阁号舍完整正立面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "魁阁号舍",
      "中央魁阁与两侧号舍七组屋顶的正面组合"
    ]
  },
  "sx_jishan_jiwang": {
    "src": "assets/plates/sx_jishan_jiwang.png",
    "alt": "稷山稷王庙献殿、钟鼓楼及后稷楼上檐 · 线稿",
    "width": 1568,
    "height": 1003,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "稷山稷王庙 · 献殿与钟鼓楼",
      "清道光重建 · 后稷楼上檐"
    ]
  },
  "xitai": {
    "src": "assets/plates/xitai.png",
    "alt": "宁海岙胡胡氏宗祠 · 戏台与勾连廊内部 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "岙胡胡氏宗祠 · 戏台与勾连廊内部",
      "柱架 · 牛腿 · 藻井"
    ]
  },
  "qiufeng": {
    "src": "assets/plates/qiufeng.png",
    "alt": "万荣后土祠秋风楼 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "后土祠 · 秋风楼正面",
      "三层楼阁 · 清代重建"
    ]
  },
  "guanque": {
    "src": "assets/plates/guanque.png",
    "alt": "永济鹳雀楼 · 2002年重建楼体 · 线稿",
    "width": 1254,
    "height": 1254,
    "color": "#a6b0b4",
    "tint": false,
    "caption": [
      "鹳雀楼正面 · 四檐三层",
      "仿唐形制 · 2002年重建"
    ]
  },
  "horyuji": {
    "src": "assets/plates/horyuji.png",
    "alt": "日本奈良法隆寺金堂单体 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c2ad78",
    "tint": false,
    "caption": [
      "法隆寺 · 金堂正面",
      "飞鸟时代 · 二重入母屋造与裳阶"
    ]
  },
  "toshodaiji": {
    "src": "assets/plates/toshodaiji.png",
    "alt": "日本奈良唐招提寺金堂单体 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#9caa76",
    "tint": false,
    "caption": [
      "唐招提寺 · 金堂正面",
      "奈良时代 · 七间寄栋造"
    ]
  },
  "byodoin": {
    "src": "assets/plates/byodoin.png",
    "alt": "日本宇治平等院凤凰堂的中堂与左右翼廊、端部楼阁完整正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#b79aca",
    "tint": false,
    "caption": [
      "平等院 · 凤凰堂正面与两翼",
      "平安时代 · 1053年"
    ]
  },
  "todaiji": {
    "src": "assets/plates/todaiji.png",
    "alt": "日本奈良东大寺南大门单体 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#68a6ad",
    "tint": false,
    "caption": [
      "东大寺 · 南大门正面",
      "镰仓时代 · 1199—1203年重建"
    ]
  },
  "kiyomizu": {
    "src": "assets/plates/kiyomizu.png",
    "alt": "京都清水寺本堂与清水舞台 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#bd8e7b",
    "tint": false,
    "caption": [
      "清水寺 · 本堂与清水舞台",
      "南面近正视 · 江户宽永十年（1633）"
    ]
  },
  "toji": {
    "src": "assets/plates/toji.png",
    "alt": "京都东寺五重塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#bd8e7b",
    "tint": false,
    "caption": [
      "东寺 · 五重塔",
      "近正视 · 江户宽永二十一年（1644）"
    ]
  }
};

for (const site of SITES) {
  if (PLATES[site.id]) site.image = {
    ...PLATES[site.id],
    caption: PLATES[site.id].caption || [site.caption[0].replace('立面示意', '线稿'), site.caption[1]],
  };
}
