/* Generated by scripts/prepare-plates.mjs; all artwork is local. */
const PLATES = {
  "hero": {
    "src": "assets/plates/hero.png",
    "alt": "佛光寺东大殿柱头铺作 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#d6ab5c",
    "tint": false
  },
  "liyeque": {
    "src": "assets/plates/liyeque.png",
    "alt": "梓潼李业阙现存单阙南面（阙顶为后世补配） · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#b79d77",
    "tint": false,
    "caption": [
      "李业阙 · 现存单阙南面",
      "东汉初年阙身，阙顶为后配"
    ]
  },
  "taishique": {
    "src": "assets/plates/taishique.png",
    "alt": "登封太室阙·西阙南面 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#b79d77",
    "tint": false,
    "caption": [
      "太室阙 · 西阙南面",
      "东汉元初五年"
    ]
  },
  "shaoshique": {
    "src": "assets/plates/shaoshique.png",
    "alt": "登封少室阙·西阙南面 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#b79d77",
    "tint": false,
    "caption": [
      "少室阙 · 西阙南面",
      "东汉子母阙"
    ]
  },
  "qimuque": {
    "src": "assets/plates/qimuque.png",
    "alt": "登封启母阙·西阙南面 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#b79d77",
    "tint": false,
    "caption": [
      "启母阙 · 西阙南面",
      "残存阙顶 · 东汉石刻"
    ]
  },
  "gaoyique": {
    "src": "assets/plates/gaoyique.png",
    "alt": "雅安高颐阙西侧子母阙近正视 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#b79d77",
    "tint": false,
    "caption": [
      "高颐阙 · 西侧子母阙",
      "近正视 · 东汉建安十四年"
    ]
  },
  "jl_jiangjunfen": {
    "src": "assets/plates/jl_jiangjunfen.png",
    "alt": "集安将军坟 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#b0a18b",
    "tint": false,
    "caption": [
      "集安将军坟 · 七级方坛石室墓",
      "高句丽 · 约5世纪"
    ]
  },
  "sx_yungang": {
    "src": "assets/plates/sx_yungang.png",
    "alt": "云冈第20窟 · 主尊坐像 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#ac8fa6",
    "tint": false,
    "caption": [
      "云冈第20窟 · 主尊坐像",
      "北魏 · 约460—470"
    ]
  },
  "songyue": {
    "src": "assets/plates/songyue.png",
    "alt": "登封嵩岳寺塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#ac8fa6",
    "tint": false,
    "caption": [
      "嵩岳寺塔 · 正面",
      "十二边形 · 十五层密檐"
    ]
  },
  "hn_gongyi": {
    "src": "assets/plates/hn_gongyi.png",
    "alt": "巩县石窟第一窟 · 中心柱主像与胁侍 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#ac8fa6",
    "tint": false,
    "caption": [
      "巩县石窟第一窟 · 中心柱主像与胁侍",
      "北魏晚期 · 石窟造像轮廓"
    ]
  },
  "xinchangdafo": {
    "src": "assets/plates/xinchangdafo.png",
    "alt": "新昌大佛寺历史石弥勒坐像与头光、身光 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#b58d67",
    "tint": false,
    "caption": [
      "新昌大佛寺 · 石弥勒像",
      "南朝齐梁 · 486—516年"
    ]
  },
  "hn_xiaonanhai": {
    "src": "assets/plates/hn_xiaonanhai.png",
    "alt": "小南海石窟 · 窟门崖面局部 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#bf8390",
    "tint": false,
    "caption": [
      "小南海石窟 · 窟门崖面局部",
      "北齐天保年间开凿 · 保留门侧残损雕刻"
    ]
  },
  "xiangtang": {
    "src": "assets/plates/xiangtang.png",
    "alt": "北响堂山第9窟大佛洞中心柱正面（西侧）主尊与火焰背光 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#bf8390",
    "tint": false,
    "caption": [
      "响堂山石窟 · 北响堂大佛洞主尊",
      "北齐 · 约550年代（推定）"
    ]
  },
  "hn_dapishan": {
    "src": "assets/plates/hn_dapishan.png",
    "alt": "大伾山摩崖大佛 · 头部至双膝可见部分 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#bf8390",
    "tint": false,
    "caption": [
      "大伾山摩崖大佛 · 头部至双膝可见部分",
      "开凿年代有争议 · 依2024年实拍现状绘制"
    ]
  },
  "sx_tianlongshan": {
    "src": "assets/plates/sx_tianlongshan.png",
    "alt": "天龙山第16窟 · 石刻前廊 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#bf8390",
    "tint": false,
    "caption": [
      "天龙山第16窟 · 石刻前廊",
      "北齐 · 仿木构局部"
    ]
  },
  "hb_yicihui": {
    "src": "assets/plates/hb_yicihui.png",
    "alt": "义慈惠石柱 · 北齐石柱及柱顶三间石殿 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#bf8390",
    "tint": false,
    "caption": [
      "定兴 · 义慈惠石柱",
      "北齐石构 · 柱顶石殿"
    ]
  },
  "hn_lingquan": {
    "src": "assets/plates/hn_lingquan.png",
    "alt": "灵泉寺大住圣窟 · 门侧成对护法局部 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#90aab6",
    "tint": false,
    "caption": [
      "灵泉寺大住圣窟 · 门侧成对护法局部",
      "隋开皇九年（589） · 迦毗罗与那罗延神王"
    ]
  },
  "hb_anjibridge": {
    "src": "assets/plates/hb_anjibridge.png",
    "alt": "赵州桥（安济桥） · 敞肩石拱桥侧立面 · 线稿",
    "width": 2005,
    "height": 784,
    "color": "#90aab6",
    "tint": false,
    "caption": [
      "赵州桥（安济桥） · 敞肩石拱桥侧立面",
      "隋 · 隋代"
    ]
  },
  "sd_simen": {
    "src": "assets/plates/sd_simen.png",
    "alt": "济南神通寺四门塔整塔 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#90aab6",
    "tint": false,
    "caption": [
      "济南神通寺四门塔整塔 · 线稿",
      "隋 · 611"
    ]
  },
  "kaiyuan": {
    "src": "assets/plates/kaiyuan.png",
    "alt": "正定开元寺须弥塔与钟楼 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#d6ab5c",
    "tint": false
  },
  "sn_xingjiao": {
    "src": "assets/plates/sn_xingjiao.png",
    "alt": "兴教寺玄奘塔（中央高塔）整塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#d6ab5c",
    "tint": false,
    "caption": [
      "兴教寺玄奘塔（中央高塔）整塔 · 线稿",
      "唐 · 669"
    ]
  },
  "xiuding": {
    "src": "assets/plates/xiuding.png",
    "alt": "修定寺塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#d6ab5c",
    "tint": false
  },
  "sn_qianling": {
    "src": "assets/plates/sn_qianling.png",
    "alt": "乾陵无字碑正面及碑座 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#d6ab5c",
    "tint": false,
    "caption": [
      "乾陵无字碑正面及碑座 · 线稿",
      "唐 · 唐代 · 立碑确年未定"
    ]
  },
  "xian": {
    "src": "assets/plates/xian.png",
    "alt": "西安大雁塔 · 小雁塔 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#d6ab5c",
    "tint": false
  },
  "sn_xiangji": {
    "src": "assets/plates/sn_xiangji.png",
    "alt": "西安香积寺善导塔现存整塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#d6ab5c",
    "tint": false,
    "caption": [
      "西安香积寺善导塔现存整塔 · 线稿",
      "唐 · 唐代 · 营建年代有异说"
    ]
  },
  "gs_bingling": {
    "src": "assets/plates/gs_bingling.png",
    "alt": "第171龛弥勒大佛 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#d6ab5c",
    "tint": false,
    "caption": [
      "第171龛弥勒大佛 · 线稿",
      "唐 · 731"
    ]
  },
  "hn_fengxue": {
    "src": "assets/plates/hn_fengxue.png",
    "alt": "风穴寺七祖塔 · 西南近正面 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#d6ab5c",
    "tint": false,
    "caption": [
      "风穴寺七祖塔 · 西南近正面",
      "唐开元二十六年（738） · 方形九层密檐砖塔"
    ]
  },
  "hb_daodejing": {
    "src": "assets/plates/hb_daodejing.png",
    "alt": "龙兴观道德经幢 · 幢身与莲座局部 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#d6ab5c",
    "tint": false,
    "caption": [
      "龙兴观道德经幢 · 幢身与莲座局部",
      "唐 · 738"
    ]
  },
  "haichunxuan": {
    "src": "assets/plates/haichunxuan.png",
    "alt": "东台海春轩塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#d6ab5c",
    "tint": false,
    "caption": [
      "海春轩塔 · 七级八角",
      "唐代古塔 · 宋代修葺"
    ]
  },
  "nanchan": {
    "src": "assets/plates/nanchan.png",
    "alt": "南禅寺大殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#d6ab5c",
    "tint": false
  },
  "sx_longshan": {
    "src": "assets/plates/sx_longshan.png",
    "alt": "龙山三天大法师窟 · 主尊局部 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#d6ab5c",
    "tint": false,
    "caption": [
      "龙山三天大法师窟 · 主尊局部",
      "唐代龛像 · 原物残貌"
    ]
  },
  "sd_longhu": {
    "src": "assets/plates/sd_longhu.png",
    "alt": "济南神通寺龙虎塔整塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#d6ab5c",
    "tint": false,
    "caption": [
      "济南神通寺龙虎塔整塔 · 线稿",
      "唐 · 唐代 · 年代未确"
    ]
  },
  "guangren": {
    "src": "assets/plates/guangren.png",
    "alt": "芮城广仁王庙正殿（龙王殿） · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#d6ab5c",
    "tint": false,
    "caption": [
      "广仁王庙正殿正面 · 据实景照片重绘",
      "唐代木构 · 五间单檐歇山顶，墙面及屋面历经修缮"
    ]
  },
  "longxingchuang": {
    "src": "assets/plates/longxingchuang.png",
    "alt": "杭州龙兴寺经幢 · 唐代幢身局部 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#d6ab5c",
    "tint": false,
    "caption": [
      "龙兴寺经幢 · 幢身局部",
      "唐开成二年 · 837年"
    ]
  },
  "chongsheng": {
    "src": "assets/plates/chongsheng.png",
    "alt": "大理崇圣寺三塔：千寻塔、南塔、北塔 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#d6ab5c",
    "tint": false,
    "caption": [
      "崇圣寺三塔 · 东向组合视图",
      "千寻塔十六层，南北小塔各十层"
    ]
  },
  "foguang": {
    "src": "assets/plates/foguang.png",
    "alt": "佛光寺东大殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#d6ab5c",
    "tint": false
  },
  "sh_tangchuang": {
    "src": "assets/plates/sh_tangchuang.png",
    "alt": "松江唐经幢 · 佛顶尊胜陀罗尼经幢 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#d6ab5c",
    "tint": false,
    "caption": [
      "八角石幢 · 层叠雕刻",
      "唐 · 大中十三年（859）"
    ]
  },
  "hlj_shideng": {
    "src": "assets/plates/hlj_shideng.png",
    "alt": "兴隆寺渤海石灯幢 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#91aca1",
    "tint": false,
    "caption": [
      "兴隆寺石灯幢 · 八角亭式灯室",
      "渤海时期 · 现存石刻"
    ]
  },
  "gongchen": {
    "src": "assets/plates/gongchen.png",
    "alt": "临安功臣塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#8f8caa",
    "tint": false
  },
  "longmen": {
    "src": "assets/plates/longmen.png",
    "alt": "龙门寺西配殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#8f8caa",
    "tint": false
  },
  "hb_zdwenmiao": {
    "src": "assets/plates/hb_zdwenmiao.png",
    "alt": "正定县文庙大成殿 · 大成殿正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#8f8caa",
    "tint": false,
    "caption": [
      "正定县文庙大成殿 · 大成殿正面",
      "五代 · 晚唐—五代"
    ]
  },
  "tiantai": {
    "src": "assets/plates/tiantai.png",
    "alt": "平顺天台庵 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#8f8caa",
    "tint": false
  },
  "dayun": {
    "src": "assets/plates/dayun.png",
    "alt": "大云院弥陀殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#8f8caa",
    "tint": false
  },
  "fuzhouwuta": {
    "src": "assets/plates/fuzhouwuta.png",
    "alt": "福州乌塔（崇妙保圣坚牢塔） · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#8f8caa",
    "tint": false,
    "caption": [
      "福州乌塔 · 崇妙保圣坚牢塔",
      "七层八角 · 五代石塔"
    ]
  },
  "wenfeng": {
    "src": "assets/plates/wenfeng.png",
    "alt": "安阳文峰塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#8f8caa",
    "tint": false
  },
  "hb_cangzhoulion": {
    "src": "assets/plates/hb_cangzhoulion.png",
    "alt": "沧州铁狮子 · 旧州现存铁狮原物（保留残缺） · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#8f8caa",
    "tint": false,
    "caption": [
      "沧州铁狮原物",
      "依2020年实拍保留残损与保护支架"
    ]
  },
  "zhakoubaita": {
    "src": "assets/plates/zhakoubaita.png",
    "alt": "杭州闸口白塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#8f8caa",
    "tint": false,
    "caption": [
      "闸口白塔",
      "九层仿木石塔 · 五代吴越"
    ]
  },
  "huqiuta": {
    "src": "assets/plates/huqiuta.png",
    "alt": "苏州虎丘云岩寺塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#8f8caa",
    "tint": false,
    "caption": [
      "虎丘 · 云岩寺塔",
      "近正面 · 五代吴越（959—961）"
    ]
  },
  "qixia": {
    "src": "assets/plates/qixia.png",
    "alt": "南京栖霞寺舍利塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#8f8caa",
    "tint": false,
    "caption": [
      "栖霞寺 · 舍利塔",
      "五层石塔 · 南唐重建"
    ]
  },
  "lingyin": {
    "src": "assets/plates/lingyin.png",
    "alt": "灵隐寺石塔与经幢 · 各取一座对照 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#8f8caa",
    "tint": false,
    "caption": [
      "石塔与经幢 · 对照线稿",
      "吴越 · 960 · 969年"
    ]
  },
  "sx_zhenguo": {
    "src": "assets/plates/sx_zhenguo.png",
    "alt": "镇国寺万佛殿 · 正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#8f8caa",
    "tint": false,
    "caption": [
      "镇国寺万佛殿 · 正面",
      "北汉天会七年 · 963"
    ]
  },
  "hualin": {
    "src": "assets/plates/hualin.png",
    "alt": "福州华林寺大殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "华林寺大殿线稿 · 面阔三间",
      "单檐歇山 · 北宋乾德二年"
    ]
  },
  "chongming": {
    "src": "assets/plates/chongming.png",
    "alt": "高平崇明寺中佛殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "中佛殿线稿 · 面阔三间",
      "七铺作 · 单檐歇山 · 北宋"
    ]
  },
  "longxing": {
    "src": "assets/plates/longxing.png",
    "alt": "正定隆兴寺摩尼殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false
  },
  "hn_jidu": {
    "src": "assets/plates/hn_jidu.png",
    "alt": "济渎庙寝宫 · 正立面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "济渎庙寝宫 · 正立面",
      "北宋开宝六年（973） · 面阔五间歇山顶"
    ]
  },
  "hn_fanta": {
    "src": "assets/plates/hn_fanta.png",
    "alt": "开封繁塔 · 现存三层主体与小塔 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "开封繁塔 · 现存三层主体与小塔",
      "宋 · 974 · 后世修补"
    ]
  },
  "sh_longhuata": {
    "src": "assets/plates/sh_longhuata.png",
    "alt": "龙华塔 · 八面七层 · 砖木楼阁塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "八面七层 · 砖木楼阁式",
      "吴越重建 · 北宋纪年（977）"
    ]
  },
  "luohanshuangta": {
    "src": "assets/plates/luohanshuangta.png",
    "alt": "苏州罗汉院双塔与正殿石柱遗迹 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "罗汉院双塔 · 石柱遗迹",
      "北宋 · 太平兴国七年始建"
    ]
  },
  "sx_youxian": {
    "src": "assets/plates/sx_youxian.png",
    "alt": "高平游仙寺毗卢殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "游仙寺 · 毗卢殿",
      "北宋淳化时期 · 约990—994"
    ]
  },
  "songyangyanqing": {
    "src": "assets/plates/songyangyanqing.png",
    "alt": "松阳延庆寺塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "松阳 · 延庆寺塔",
      "六面七级 · 底层副阶重檐"
    ]
  },
  "yuanqi": {
    "src": "assets/plates/yuanqi.png",
    "alt": "原起寺青龙塔与大雄宝殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false
  },
  "gd_meian": {
    "src": "assets/plates/gd_meian.png",
    "alt": "梅庵大雄宝殿完整殿体 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "梅庵大雄宝殿完整殿体 · 线稿",
      "宋 · 北宋"
    ]
  },
  "ruiguang": {
    "src": "assets/plates/ruiguang.png",
    "alt": "苏州瑞光塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "瑞光塔 · 七级八面",
      "北宋塔身 · 木檐后修"
    ]
  },
  "baoguo": {
    "src": "assets/plates/baoguo.png",
    "alt": "宁波保国寺大殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false
  },
  "sx_chongqing": {
    "src": "assets/plates/sx_chongqing.png",
    "alt": "长子崇庆寺千佛殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "崇庆寺 · 千佛殿",
      "北宋大中祥符九年 · 1016"
    ]
  },
  "hb_xiude": {
    "src": "assets/plates/hb_xiude.png",
    "alt": "修德寺塔 · 现存楼阁与花塔混合式砖塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "曲阳 · 修德寺塔",
      "现状塔身 · 楼阁与花塔合构"
    ]
  },
  "jiwang": {
    "src": "assets/plates/jiwang.png",
    "alt": "万荣稷王庙正殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "万荣稷王庙 · 正殿",
      "五间庑殿 · 北宋遗构"
    ]
  },
  "haiqing": {
    "src": "assets/plates/haiqing.png",
    "alt": "连云港海清寺阿育王塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "海清寺 · 阿育王塔",
      "八面九级砖塔 · 北宋天圣元年重建"
    ]
  },
  "hb_tuoluoni": {
    "src": "assets/plates/hb_tuoluoni.png",
    "alt": "赵州陀罗尼经幢 · 七级石经幢 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "赵州陀罗尼经幢 · 七级石经幢",
      "宋 · 1038"
    ]
  },
  "lingxiao": {
    "src": "assets/plates/lingxiao.png",
    "alt": "正定天宁寺凌霄塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false
  },
  "hn_tieta": {
    "src": "assets/plates/hn_tieta.png",
    "alt": "开封铁塔 · 祐国寺琉璃塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "开封铁塔 · 祐国寺琉璃塔",
      "宋 · 1049"
    ]
  },
  "fotou": {
    "src": "assets/plates/fotou.png",
    "alt": "平顺佛头寺 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "佛殿线稿 · 面阔三间",
      "单檐歇山 · 现存金构"
    ]
  },
  "baosheng": {
    "src": "assets/plates/baosheng.png",
    "alt": "甪直保圣寺罗汉塑像单尊与相邻山石塑壁局部 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "保圣寺 · 罗汉塑像与山石塑壁（局部）",
      "北宋 · 后世修补"
    ]
  },
  "hb_puli": {
    "src": "assets/plates/hb_puli.png",
    "alt": "普利寺塔 · 方形七层砖塔与高石台基 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "临城普利寺塔",
      "方形七层塔身与平坐檐；不绘外围高台全貌"
    ]
  },
  "liaodi": {
    "src": "assets/plates/liaodi.png",
    "alt": "定州开元寺料敌塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false
  },
  "sd_pizhi": {
    "src": "assets/plates/sd_pizhi.png",
    "alt": "济南灵岩寺辟支塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "八角九层 · 下三层重檐",
      "北宋重建 · 现存砖塔"
    ]
  },
  "hb_yuquan": {
    "src": "assets/plates/hb_yuquan.png",
    "alt": "当阳玉泉寺十三层铁塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "当阳玉泉寺十三层铁塔 · 线稿",
      "北宋 · 1061 · 塔刹后配"
    ]
  },
  "hn_xiangshan": {
    "src": "assets/plates/hn_xiangshan.png",
    "alt": "香山寺大悲观音大士塔 · 现状可见塔身 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "香山寺大悲观音大士塔 · 现状可见塔身",
      "北宋熙宁元年重建 · 下部遮挡处留白"
    ]
  },
  "sx_kaihua": {
    "src": "assets/plates/sx_kaihua.png",
    "alt": "高平开化寺大雄宝殿 · 线稿",
    "width": 1518,
    "height": 1036,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "开化寺 · 大雄宝殿",
      "北宋熙宁六年 · 1073"
    ]
  },
  "hb_jingzhouta": {
    "src": "assets/plates/hb_jingzhouta.png",
    "alt": "开福寺舍利塔 · 八角十三层楼阁式塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "景州塔正面",
      "十三层八角塔身与铁刹网、铜葫芦"
    ]
  },
  "sh_fangta": {
    "src": "assets/plates/sh_fangta.png",
    "alt": "松江兴圣教寺塔 · 方塔园 · 九层方塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "方形九层 · 砖木塔",
      "北宋 · 熙宁、元祐年间"
    ]
  },
  "qinglian": {
    "src": "assets/plates/qinglian.png",
    "alt": "晋城青莲寺上寺释迦殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "上寺释迦殿线稿 · 面阔三间",
      "单檐歇山 · 北宋元祐四年"
    ]
  },
  "sx_wubian": {
    "src": "assets/plates/sx_wubian.png",
    "alt": "太谷无边寺白塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "无边寺 · 白塔",
      "北宋元祐五年 · 八角楼阁塔"
    ]
  },
  "hn_chongfa": {
    "src": "assets/plates/hn_chongfa.png",
    "alt": "崇法寺塔 · 近正面 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "崇法寺塔 · 近正面",
      "北宋绍圣五年（1098）竣工 · 八角九层楼阁式砖塔"
    ]
  },
  "anyue": {
    "src": "assets/plates/anyue.png",
    "alt": "安岳毗卢洞水月观音（紫竹观音） · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "安岳石刻 · 毗卢洞水月观音",
      "宋代 · 紫竹观音游戏坐"
    ]
  },
  "hn_xiaoshang": {
    "src": "assets/plates/hn_xiaoshang.png",
    "alt": "小商桥 · 石拱桥侧立面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "小商桥 · 石拱桥侧立面",
      "宋代主体、历代修缮 · 一主拱与左右各一腹拱"
    ]
  },
  "sn_daqin": {
    "src": "assets/plates/sn_daqin.png",
    "alt": "周至大秦寺塔现存整塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "周至大秦寺塔现存整塔 · 线稿",
      "宋 · 宋代 · 确年未定"
    ]
  },
  "jinci": {
    "src": "assets/plates/jinci.png",
    "alt": "晋祠圣母殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "晋祠 · 圣母殿",
      "北宋 · 七间重檐与八根盘龙柱"
    ]
  },
  "sx_faxing": {
    "src": "assets/plates/sx_faxing.png",
    "alt": "山西长子法兴寺圆觉殿中央释迦牟尼坐像及莲座、台座 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "法兴寺圆觉殿 · 释迦牟尼坐像",
      "北宋政和元年（1111）宋塑 · 随寺迁建现状"
    ]
  },
  "hn_chuzu": {
    "src": "assets/plates/hn_chuzu.png",
    "alt": "少林寺初祖庵 · 初祖庵大殿正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "少林寺初祖庵 · 初祖庵大殿正面",
      "宋 · 1125"
    ]
  },
  "liuhe": {
    "src": "assets/plates/liuhe.png",
    "alt": "杭州六和塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false
  },
  "xuanmiao": {
    "src": "assets/plates/xuanmiao.png",
    "alt": "苏州玄妙观三清殿（非山门） · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "玄妙观 · 三清殿正面",
      "南宋淳熙六年（1179） · 九间重檐歇山"
    ]
  },
  "dazu": {
    "src": "assets/plates/dazu.png",
    "alt": "大足宝顶山第8号龛千手观音主尊 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "大足石刻 · 宝顶山千手观音",
      "南宋 · 主尊与放射手臂局部"
    ]
  },
  "feilaifeng": {
    "src": "assets/plates/feilaifeng.png",
    "alt": "杭州飞来峰第68龛布袋弥勒及邻近四尊罗汉（局部） · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "飞来峰第68龛 · 布袋弥勒与邻近罗汉（局部）",
      "南宋（传统断代，亦有元初说）"
    ]
  },
  "zijinan": {
    "src": "assets/plates/zijinan.png",
    "alt": "苏州东山紫金庵第十尊者半托迦罗汉塑像上身局部 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "紫金庵 · 半托迦尊者（上身局部）",
      "宋—明 · 历代修护"
    ]
  },
  "feiying": {
    "src": "assets/plates/feiying.png",
    "alt": "湖州飞英塔外塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "飞英塔 · 外塔",
      "完整外立面 · 南宋重建"
    ]
  },
  "fj_renshou": {
    "src": "assets/plates/fj_renshou.png",
    "alt": "泉州开元寺仁寿塔（西塔）整塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "泉州开元寺仁寿塔（西塔）整塔 · 线稿",
      "南宋 · 1228—1237"
    ]
  },
  "fj_zhenguo": {
    "src": "assets/plates/fj_zhenguo.png",
    "alt": "泉州开元寺镇国塔（东塔）整塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "泉州开元寺镇国塔（东塔）整塔 · 线稿",
      "南宋 · 1238—1250"
    ]
  },
  "baziqiao": {
    "src": "assets/plates/baziqiao.png",
    "alt": "绍兴八字桥南侧近正面石梁桥与两岸石阶 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "八字桥 · 南侧石梁桥与沿河石阶",
      "南宋 · 宝祐四年（1256）重建"
    ]
  },
  "geyuan": {
    "src": "assets/plates/geyuan.png",
    "alt": "涞源阁院寺文殊殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "阁院寺文殊殿线稿 · 面阔三间",
      "单檐歇山 · 辽代木构"
    ]
  },
  "dule": {
    "src": "assets/plates/dule.png",
    "alt": "天津独乐寺观音阁 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "独乐寺观音阁正面 · 据实景照片重绘",
      "辽统和二年（984）重建 · 面阔五间，外观两层、内部三层"
    ]
  },
  "jl_nongan": {
    "src": "assets/plates/jl_nongan.png",
    "alt": "农安辽塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "农安辽塔 · 八角十三层密檐",
      "辽代遗存 · 现貌历经现代修缮"
    ]
  },
  "kaishan": {
    "src": "assets/plates/kaishan.png",
    "alt": "高碑店开善寺大雄宝殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false
  },
  "fengguo": {
    "src": "assets/plates/fengguo.png",
    "alt": "义县奉国寺大雄殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "奉国寺大雄殿线稿 · 面阔九间",
      "单檐庑殿 · 辽开泰九年"
    ]
  },
  "zhuozhou": {
    "src": "assets/plates/zhuozhou.png",
    "alt": "涿州双塔（云居寺塔与智度寺塔） · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "云居寺塔 · 智度寺塔",
      "北塔六层 · 南塔五层"
    ]
  },
  "huayan": {
    "src": "assets/plates/huayan.png",
    "alt": "大同华严寺大雄宝殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false
  },
  "qingzhou": {
    "src": "assets/plates/qingzhou.png",
    "alt": "辽庆州白塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "辽庆州白塔",
      "八角七级，北立面"
    ]
  },
  "huanghuatan": {
    "src": "assets/plates/huanghuatan.png",
    "alt": "辽宁朝阳黄花滩塔·东南券门面 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "黄花滩塔 · 辽宁朝阳",
      "十三层密檐 · 修缮后现貌"
    ]
  },
  "yingxian": {
    "src": "assets/plates/yingxian.png",
    "alt": "应县木塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#c8442b",
    "tint": false
  },
  "hb_nanansi": {
    "src": "assets/plates/hb_nanansi.png",
    "alt": "南安寺塔 · 十三层密檐砖塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "蔚县南安寺塔",
      "八角十三层密檐塔与仰莲塔座"
    ]
  },
  "tj_jizhou_baita": {
    "src": "assets/plates/tj_jizhou_baita.png",
    "alt": "天津蓟县白塔 · 八角砖塔与覆钵式塔身 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "蓟县白塔 · 楼阁与覆钵形制",
      "辽至清 · 历代修缮现貌"
    ]
  },
  "ln_liaoyang": {
    "src": "assets/plates/ln_liaoyang.png",
    "alt": "辽阳白塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "辽阳白塔 · 八角十三层密檐",
      "辽代 · 塔身佛教浮雕"
    ]
  },
  "ln_chongxing": {
    "src": "assets/plates/ln_chongxing.png",
    "alt": "北镇崇兴寺双塔 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "崇兴寺 · 辽代双塔",
      "西塔与东塔 · 各十三层密檐"
    ]
  },
  "tianning": {
    "src": "assets/plates/tianning.png",
    "alt": "北京天宁寺塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#c8442b",
    "tint": false
  },
  "huilong": {
    "src": "assets/plates/huilong.png",
    "alt": "平顺侯壁村回龙寺正殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "正殿线稿 · 面阔三间",
      "单檐悬山 · 宋金之际"
    ]
  },
  "shanhua": {
    "src": "assets/plates/shanhua.png",
    "alt": "大同善化寺普贤阁 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false
  },
  "sx_xixi_erxian": {
    "src": "assets/plates/sx_xixi_erxian.png",
    "alt": "陵川西溪二仙庙后殿（正殿） · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "西溪二仙庙 · 后殿",
      "金代 · 1142年起重建"
    ]
  },
  "sx_chongfu": {
    "src": "assets/plates/sx_chongfu.png",
    "alt": "崇福寺弥陀殿 · 正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "崇福寺弥陀殿 · 正面",
      "七间单檐歇山 · 金"
    ]
  },
  "sx_macun": {
    "src": "assets/plates/sx_macun.png",
    "alt": "马村一号墓妇人启门砖雕壁面局部 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "马村砖雕墓 · 一号墓妇人启门",
      "金代 · 墓室砖雕局部线描"
    ]
  },
  "yuanjue": {
    "src": "assets/plates/yuanjue.png",
    "alt": "浑源圆觉寺塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "圆觉寺塔线稿 · 八角九级",
      "密檐式砖塔 · 金正隆三年"
    ]
  },
  "chunhua": {
    "src": "assets/plates/chunhua.png",
    "alt": "平顺淳化寺正殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false
  },
  "huata": {
    "src": "assets/plates/huata.png",
    "alt": "正定广惠寺华塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#c8442b",
    "tint": false
  },
  "sx_pingyaowenmiao": {
    "src": "assets/plates/sx_pingyaowenmiao.png",
    "alt": "平遥文庙 · 大成殿正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "平遥文庙 · 大成殿正面",
      "金 · 1163"
    ]
  },
  "yanshan": {
    "src": "assets/plates/yanshan.png",
    "alt": "繁峙岩山寺文殊殿（南殿） · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "岩山寺文殊殿正面 · 据实景照片重绘",
      "金代遗构，元延祐二年（1315）重修 · 五间单檐歇山顶"
    ]
  },
  "hn_baima": {
    "src": "assets/plates/hn_baima.png",
    "alt": "白马寺齐云塔 · 方形十三层密檐塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "白马寺齐云塔 · 方形十三层密檐塔",
      "金大定十五年（1175）重建"
    ]
  },
  "hn_baolun": {
    "src": "assets/plates/hn_baolun.png",
    "alt": "宝轮寺塔 · 南立面 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "宝轮寺塔 · 南立面",
      "金大定十七年（1177） · 方形十三层密檐砖塔"
    ]
  },
  "wangbao": {
    "src": "assets/plates/wangbao.png",
    "alt": "高平王报二郎庙金代戏台正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "王报二郎庙 · 金代戏台",
      "金 · 大定二十三年（1183）"
    ]
  },
  "jingtusi": {
    "src": "assets/plates/jingtusi.png",
    "alt": "应县净土寺大雄宝殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "净土寺大雄宝殿正面 · 据实景照片重绘",
      "金大定二十四年重修（1184）· 三间单檐歇山顶"
    ]
  },
  "hn_fengxian": {
    "src": "assets/plates/hn_fengxian.png",
    "alt": "奉仙观三清殿 · 五间悬山大殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "奉仙观三清殿 · 五间悬山大殿",
      "金大定二十四年（1184）"
    ]
  },
  "hb_linji": {
    "src": "assets/plates/hb_linji.png",
    "alt": "临济寺澄灵塔 · 八角九级密檐塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "临济寺澄灵塔 · 八角九级密檐塔",
      "金 · 1185大修"
    ]
  },
  "bj_lugou": {
    "src": "assets/plates/bj_lugou.png",
    "alt": "北京卢沟桥 · 十一孔石桥侧向全貌 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "北京卢沟桥 · 十一孔石拱",
      "金 · 1192建成，明清修缮"
    ]
  },
  "hongfu": {
    "src": "assets/plates/hongfu.png",
    "alt": "定襄洪福寺大雄宝殿（毗卢殿） · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "洪福寺大雄宝殿正面 · 据实景照片重绘",
      "金代遗构 · 面阔五间，单檐悬山顶"
    ]
  },
  "yanqing": {
    "src": "assets/plates/yanqing.png",
    "alt": "五台善文村延庆寺大佛殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "延庆寺大佛殿正面 · 五台善文村",
      "金代遗构 · 三间歇山顶，现状保留后世柱头兽面"
    ]
  },
  "sx_taifu": {
    "src": "assets/plates/sx_taifu.png",
    "alt": "汾阳太符观昊天玉皇上帝殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "太符观 · 昊天玉皇上帝殿",
      "金代 · 三间单檐歇山"
    ]
  },
  "yongle": {
    "src": "assets/plates/yongle.png",
    "alt": "芮城永乐宫三清殿（无极殿） · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "永乐宫 · 三清殿正面",
      "七间庑殿 · 中统三年"
    ]
  },
  "hn_guanxing": {
    "src": "assets/plates/hn_guanxing.png",
    "alt": "登封观星台 · 台体与石圭正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "登封观星台 · 台体与石圭正面",
      "元 · 1276"
    ]
  },
  "bj_miaoying": {
    "src": "assets/plates/bj_miaoying.png",
    "alt": "北京妙应寺白塔 · 覆钵式塔与十字折角基座 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "北京妙应寺白塔 · 覆钵式塔",
      "元 · 1271—1279"
    ]
  },
  "fenghuangsi": {
    "src": "assets/plates/fenghuangsi.png",
    "alt": "杭州凤凰寺元代核心礼拜殿（后窑殿）屋顶群与可见上部 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "凤凰寺礼拜殿 · 实景可见屋顶群",
      "元代核心殿，历代修缮 · 三攒尖顶与上部墙身"
    ]
  },
  "sx_jishi": {
    "src": "assets/plates/sx_jishi.png",
    "alt": "高平姬氏民居元代正房 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "姬氏民居 · 三间元代正房",
      "至元三十一年 · 1294"
    ]
  },
  "hn_yuzhoutianning": {
    "src": "assets/plates/hn_yuzhoutianning.png",
    "alt": "禹州天宁万寿寺大殿 · 现状近正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "禹州天宁万寿寺大殿 · 现状近正面",
      "元大德三年（1299）重建 · 三间单檐歇山顶"
    ]
  },
  "jiutian": {
    "src": "assets/plates/jiutian.png",
    "alt": "九天圣母庙献殿 · 长边侧立面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "献殿线稿 · 侧立面 · 进深五间",
      "庑殿顶 · 正脊沿进深 · 元"
    ]
  },
  "hn_huishan": {
    "src": "assets/plates/hn_huishan.png",
    "alt": "登封会善寺 · 元代大殿正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "登封会善寺 · 元代大殿正面",
      "元 · 元代"
    ]
  },
  "hb_shijia": {
    "src": "assets/plates/hb_shijia.png",
    "alt": "释迦寺 · 三间单檐歇山大雄宝殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "释迦寺中殿",
      "元代三间单檐歇山大雄宝殿正面"
    ]
  },
  "sx_jiangzhou_datang": {
    "src": "assets/plates/sx_jiangzhou_datang.png",
    "alt": "绛州大堂元代正堂南立面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "绛州大堂 · 州署正堂",
      "元代 · 七间悬山"
    ]
  },
  "sx_fusheng": {
    "src": "assets/plates/sx_fusheng.png",
    "alt": "新绛福胜寺弥陀殿北立面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "福胜寺 · 弥陀殿北立面",
      "元代遗构 · 明代修缮"
    ]
  },
  "sx_zezhou_yuhuang": {
    "src": "assets/plates/sx_zezhou_yuhuang.png",
    "alt": "府城玉皇庙二十八宿彩塑之虚日鼠 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "泽州玉皇庙 · 虚日鼠",
      "元代 · 二十八宿代表彩塑"
    ]
  },
  "hb_ciyunge": {
    "src": "assets/plates/hb_ciyunge.png",
    "alt": "慈云阁 · 现存两层三间楼阁 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "定兴 · 慈云阁",
      "两层三间 · 元大德十年重建"
    ]
  },
  "yongan": {
    "src": "assets/plates/yongan.png",
    "alt": "浑源永安禅寺传法正宗殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "传法正宗殿线稿 · 面阔五间",
      "单檐庑殿 · 元延祐二年"
    ]
  },
  "yanfu": {
    "src": "assets/plates/yanfu.png",
    "alt": "武义延福寺大殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "延福寺 · 大殿",
      "元延祐四年 · 重檐歇山"
    ]
  },
  "jinhuatianning": {
    "src": "assets/plates/jinhuatianning.png",
    "alt": "金华天宁寺大殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "金华天宁寺 · 大殿",
      "元延祐五年 · 单檐歇山"
    ]
  },
  "sh_zhenru": {
    "src": "assets/plates/sh_zhenru.png",
    "alt": "真如寺大殿 · 三间单檐歇山 · 元代木构 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "大殿正立面 · 面阔三间",
      "元 · 延祐七年（1320）"
    ]
  },
  "xiayu": {
    "src": "assets/plates/xiayu.png",
    "alt": "夏禹神祠正殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false
  },
  "duanliang": {
    "src": "assets/plates/duanliang.png",
    "alt": "苏州虎丘云岩寺二山门（断梁殿） · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "虎丘二山门 · 断梁殿正面",
      "元至元四年（1338）重建 · 三间单檐歇山"
    ]
  },
  "sx_doudafu": {
    "src": "assets/plates/sx_doudafu.png",
    "alt": "太原窦大夫祠 · 献亭与大殿正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "太原窦大夫祠 · 献亭与大殿正面",
      "元 · 至正三年（1343）重建"
    ]
  },
  "bj_juyong_yuntai": {
    "src": "assets/plates/bj_juyong_yuntai.png",
    "alt": "北京居庸关云台 · 元代过街塔基南面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "居庸关云台 · 现存过街塔基",
      "元 · 1342—1345营建"
    ]
  },
  "hb_beiyue": {
    "src": "assets/plates/hb_beiyue.png",
    "alt": "北岳庙 · 德宁之殿正立面（含回廊、台基） · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "曲阳 · 北岳庙德宁之殿",
      "元代木构 · 重檐庑殿"
    ]
  },
  "xuanyuan": {
    "src": "assets/plates/xuanyuan.png",
    "alt": "苏州东山杨湾轩辕宫正殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "东山杨湾 · 轩辕宫正殿",
      "三间单檐歇山 · 元代特征与明清修建并存"
    ]
  },
  "shisi": {
    "src": "assets/plates/shisi.png",
    "alt": "景宁时思寺大殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "时思寺 · 大殿",
      "元至正十六年 · 重檐歇山"
    ]
  },
  "jijian": {
    "src": "assets/plates/jijian.png",
    "alt": "苏州天池山寂鉴寺西天寺石殿（1357） · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "寂鉴寺 · 西天寺石殿正面",
      "元至正十七年（1357） · 三间石构仿木"
    ]
  },
  "sx_jishan_qinglong": {
    "src": "assets/plates/sx_jishan_qinglong.png",
    "alt": "稷山青龙寺腰殿西壁三世佛壁画局部 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c98a3f",
    "tint": false,
    "caption": [
      "青龙寺 · 腰殿西壁三世佛局部",
      "元末—明初 · 壁画线描转绘"
    ]
  },
  "sx_pingyaowall": {
    "src": "assets/plates/sx_pingyaowall.png",
    "alt": "平遥城墙 · 迎薰门及相邻墙段 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "平遥城墙 · 迎薰门及相邻墙段",
      "明清 · 明清"
    ]
  },
  "sn_hancheng": {
    "src": "assets/plates/sn_hancheng.png",
    "alt": "韩城文庙大成殿整殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "韩城文庙大成殿整殿 · 线稿",
      "明 · 1371重建 · 后世修护"
    ]
  },
  "yuhuang": {
    "src": "assets/plates/yuhuang.png",
    "alt": "蔚州玉皇阁 · 线稿",
    "width": 1584,
    "height": 993,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "蔚州玉皇阁 · 正面",
      "三檐两层 · 面阔五间"
    ]
  },
  "xianwall": {
    "src": "assets/plates/xianwall.png",
    "alt": "西安城墙安定门箭楼西立面及中央单券门洞墙段 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "西安城墙 · 安定门箭楼与中央券洞",
      "明代城垣 · 明清及近现代修葺"
    ]
  },
  "xianzhonggu": {
    "src": "assets/plates/xianzhonggu.png",
    "alt": "西安钟楼与鼓楼并置合绘（左钟楼、右鼓楼） · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "西安钟楼 · 鼓楼",
      "双主体组合图，并非实景相邻"
    ]
  },
  "linggu": {
    "src": "assets/plates/linggu.png",
    "alt": "南京灵谷寺无梁殿单体正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "灵谷寺无梁殿 · 砖券大殿正面",
      "明代遗构 · 重檐九脊与三塔脊饰"
    ]
  },
  "sx_chongshan": {
    "src": "assets/plates/sx_chongshan.png",
    "alt": "太原崇善寺大悲殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "崇善寺 · 大悲殿",
      "明洪武 · 七间重檐庑殿"
    ]
  },
  "fj_chongwu": {
    "src": "assets/plates/fj_chongwu.png",
    "alt": "崇武古城南门及相邻短段城墙 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "崇武古城南门及相邻短段城墙 · 线稿",
      "明 · 始建1387 · 历代修缮"
    ]
  },
  "sx_jiulongbi": {
    "src": "assets/plates/sx_jiulongbi.png",
    "alt": "大同九龙壁 · 九龙琉璃照壁正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "大同九龙壁 · 九龙琉璃照壁正面",
      "明 · 洪武二十五年（1392）"
    ]
  },
  "shuanglin": {
    "src": "assets/plates/shuanglin.png",
    "alt": "平遥双林寺天王殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false
  },
  "hb_zixiao": {
    "src": "assets/plates/hb_zixiao.png",
    "alt": "紫霄宫紫霄大殿与正面台基 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "紫霄宫紫霄大殿与正面台基 · 线稿",
      "明 · 明永乐年间"
    ]
  },
  "hb_jindian": {
    "src": "assets/plates/hb_jindian.png",
    "alt": "武当山天柱峰明代金殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "武当山天柱峰明代金殿 · 线稿",
      "明 · 1416"
    ]
  },
  "tiantan": {
    "src": "assets/plates/tiantan.png",
    "alt": "北京天坛祈年殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false
  },
  "hb_jimingyi": {
    "src": "assets/plates/hb_jimingyi.png",
    "alt": "鸡鸣驿城 · 东门城台与两翼古城墙 · 线稿",
    "width": 1448,
    "height": 1086,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "怀来鸡鸣驿城 · 东门",
      "门台与两翼墙段；城楼为修复现状"
    ]
  },
  "bj_changling": {
    "src": "assets/plates/bj_changling.png",
    "alt": "北京长陵 · 祾恩殿九开间重檐庑殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "长陵 · 九开间祾恩殿",
      "明永乐至宣德 · 1416—1427营建沿革"
    ]
  },
  "baoen": {
    "src": "assets/plates/baoen.png",
    "alt": "南京大报恩寺旧琉璃塔（据1915年土山湾模型绘制） · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "九层八面 · 据土山湾旧塔模型绘制",
      "原塔已毁 · 非现代玻璃新塔"
    ]
  },
  "bj_zhihua": {
    "src": "assets/plates/bj_zhihua.png",
    "alt": "北京智化寺 · 如来殿与万佛阁南面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "北京智化寺 · 如来殿与万佛阁",
      "明 · 1443—1444始建"
    ]
  },
  "hunyuanwenmiao": {
    "src": "assets/plates/hunyuanwenmiao.png",
    "alt": "浑源文庙大成殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "文庙大成殿线稿 · 面阔五间",
      "单檐庑殿 · 现存明代遗构"
    ]
  },
  "bj_zhenjue": {
    "src": "assets/plates/bj_zhenjue.png",
    "alt": "北京真觉寺金刚宝座 · 南面五层佛龛与密檐石塔 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "北京真觉寺金刚宝座 · 南面",
      "明 · 1473"
    ]
  },
  "hb_xuanhuaqingyuan": {
    "src": "assets/plates/hb_xuanhuaqingyuan.png",
    "alt": "宣化清远楼 · 十字歇山三重檐钟楼及砖台 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "清远楼南面",
      "三重檐十字歇山顶与砖台券洞"
    ]
  },
  "yn_jianshui": {
    "src": "assets/plates/yn_jianshui.png",
    "alt": "建水文庙先师殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "建水文庙先师殿 · 线稿 · 待用户验收",
      "明 · 弘治年间"
    ]
  },
  "sx_yuci_chenghuang": {
    "src": "assets/plates/sx_yuci_chenghuang.png",
    "alt": "榆次城隍庙玄鉴楼北侧乐楼与戏台组合 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "榆次城隍庙 · 玄鉴楼北侧",
      "明代 · 乐楼与过路戏台"
    ]
  },
  "zhaoling": {
    "src": "assets/plates/zhaoling.png",
    "alt": "福建仙游顶东湖村东湖昭灵宫现存单殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "仙游昭灵宫 · 单殿正面",
      "明代（待考） · 单檐歇山"
    ]
  },
  "sn_yanan": {
    "src": "assets/plates/sn_yanan.png",
    "alt": "延安宝塔（岭山寺塔）现存整塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "延安宝塔（岭山寺塔）现存整塔 · 线稿",
      "明 · 明代重修 · 确年未定"
    ]
  },
  "gx_dashi": {
    "src": "assets/plates/gx_dashi.png",
    "alt": "合浦永安大士阁前阁及相连后阁 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "合浦永安大士阁前阁及相连后阁 · 线稿",
      "明 · 明代"
    ]
  },
  "gs_jiayuguan": {
    "src": "assets/plates/gs_jiayuguan.png",
    "alt": "西侧嘉峪关楼与门台 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "西侧嘉峪关楼与门台 · 线稿",
      "明 · 弘治—正德"
    ]
  },
  "gs_dafo_tuta": {
    "src": "assets/plates/gs_dafo_tuta.png",
    "alt": "弥陀千佛塔露明塔身与塔刹 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "弥陀千佛塔露明塔身与塔刹 · 线稿",
      "明 · 明代"
    ]
  },
  "gongzhu": {
    "src": "assets/plates/gongzhu.png",
    "alt": "繁峙公主寺大雄宝殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "公主寺大雄宝殿正面 · 据实景照片重绘",
      "明弘治十六年（1503）重修 · 三间单檐悬山顶，檐下无斗栱"
    ]
  },
  "hb_xtkaiyuan": {
    "src": "assets/plates/hb_xtkaiyuan.png",
    "alt": "邢台开元寺 · 古开元寺菩萨殿（第三殿/释迦牟尼殿），完整正面及四根滚龙石柱 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "邢台开元寺 · 菩萨殿",
      "五间硬山殿与四根滚龙石柱正面"
    ]
  },
  "sx_jiexiu_houtu": {
    "src": "assets/plates/sx_jiexiu_houtu.png",
    "alt": "介休后土庙三清楼北面戏台与八字影壁 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "介休后土庙 · 三清楼北面戏台",
      "明清 · 戏台与八字影壁"
    ]
  },
  "tiefo": {
    "src": "assets/plates/tiefo.png",
    "alt": "高平铁佛寺正殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "正殿线稿 · 面阔三间",
      "单檐悬山 · 明代"
    ]
  },
  "feihong": {
    "src": "assets/plates/feihong.png",
    "alt": "广胜寺飞虹塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7290bd",
    "tint": false
  },
  "hb_xianling": {
    "src": "assets/plates/hb_xianling.png",
    "alt": "明显陵棂星门石坊及相连琉璃影壁 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "明显陵棂星门石坊及相连琉璃影壁 · 线稿",
      "明 · 明嘉靖年间"
    ]
  },
  "taimiao": {
    "src": "assets/plates/taimiao.png",
    "alt": "北京太庙享殿（前殿） · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "北京太庙 · 享殿",
      "十一间面阔 · 三层须弥座"
    ]
  },
  "fuzhoubaita": {
    "src": "assets/plates/fuzhoubaita.png",
    "alt": "福州白塔（报恩定光多宝塔） · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "福州白塔 · 定光塔",
      "七层八角 · 明代重建"
    ]
  },
  "sx_haihui": {
    "src": "assets/plates/sx_haihui.png",
    "alt": "阳城海会寺小砖塔与明代琉璃大塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "海会寺 · 小砖塔与琉璃大塔",
      "五代—宋小塔 · 明嘉靖至隆庆大塔"
    ]
  },
  "gx_zhenwu": {
    "src": "assets/plates/gx_zhenwu.png",
    "alt": "经略台真武阁完整阁体 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "经略台真武阁完整阁体 · 线稿",
      "明 · 1573"
    ]
  },
  "guanyintang": {
    "src": "assets/plates/guanyintang.png",
    "alt": "长治观音堂观音主像及天宫悬塑局部 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "长治观音堂 · 观音与天宫悬塑局部",
      "明万历年间 · 彩塑与悬塑"
    ]
  },
  "xuankong": {
    "src": "assets/plates/xuankong.png",
    "alt": "浑源悬空寺现存明清崖壁建筑群 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "悬空寺 · 崖壁建筑群",
      "明清遗构 · 南北楼与凌空栈道"
    ]
  },
  "hn_bigan": {
    "src": "assets/plates/hn_bigan.png",
    "alt": "比干庙享殿 · 前部可见立面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "比干庙享殿 · 前部可见立面",
      "明清重建、续修 · 依据2024年正面实拍"
    ]
  },
  "hb_wahuang": {
    "src": "assets/plates/hb_wahuang.png",
    "alt": "娲皇宫及石刻 · 悬崖前娲皇阁及承托石券 · 线稿",
    "width": 1448,
    "height": 1086,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "涉县娲皇宫 · 娲皇阁",
      "三层木阁与下层前廊的四道檐线"
    ]
  },
  "im_dazhao": {
    "src": "assets/plates/im_dazhao.png",
    "alt": "呼和浩特大召寺大雄宝殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "呼和浩特大召寺大雄宝殿 · 线稿 · 待用户验收",
      "明清 · 明清"
    ]
  },
  "gd_zumiao": {
    "src": "assets/plates/gd_zumiao.png",
    "alt": "佛山祖庙三门立面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "佛山祖庙三门立面 · 线稿",
      "明清 · 明清"
    ]
  },
  "sn_chongwen": {
    "src": "assets/plates/sn_chongwen.png",
    "alt": "泾阳崇文塔现存整塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "泾阳崇文塔现存整塔 · 线稿",
      "明 · 1591—1608"
    ]
  },
  "sx_yongzuo": {
    "src": "assets/plates/sx_yongzuo.png",
    "alt": "太原永祚寺双塔 · 文峰塔与宣文塔 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "太原永祚寺双塔 · 文峰塔与宣文塔",
      "明 · 明万历"
    ]
  },
  "hn_luwang": {
    "src": "assets/plates/hn_luwang.png",
    "alt": "潞简王墓 · 潞藩佳城石坊 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "潞简王墓 · 潞藩佳城石坊",
      "明万历时期 · 三门石坊与双石柱"
    ]
  },
  "rulong": {
    "src": "assets/plates/rulong.png",
    "alt": "庆元月山如龙桥完整侧立面、木拱下缘与桥头钟楼 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "如龙桥 · 木拱桥廊与桥头楼阁",
      "明 · 天启五年（1625）修造"
    ]
  },
  "ln_dazheng": {
    "src": "assets/plates/ln_dazheng.png",
    "alt": "沈阳故宫大政殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "沈阳故宫 · 大政殿",
      "清初 · 八角重檐攒尖"
    ]
  },
  "quanzhoukaiyuan": {
    "src": "assets/plates/quanzhoukaiyuan.png",
    "alt": "泉州开元寺大雄宝殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "泉州开元寺 · 大雄宝殿",
      "明崇祯十年重修 · 九间百柱殿"
    ]
  },
  "xiaoxitian": {
    "src": "assets/plates/xiaoxitian.png",
    "alt": "隰县小西天大雄宝殿中央主龛、悬塑楼阁与群像局部 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "小西天 · 大雄宝殿悬塑局部",
      "明末清初 · 主龛与天宫楼阁"
    ]
  },
  "tj_wenmiao": {
    "src": "assets/plates/tj_wenmiao.png",
    "alt": "天津文庙 · 府庙大成殿中部立面与丹陛 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "天津文庙 · 大成殿中部与丹陛",
      "明清遗构 · 1436为文庙初创"
    ]
  },
  "xianshen": {
    "src": "assets/plates/xianshen.png",
    "alt": "介休祆神楼过街楼与乐楼组合近正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "介休祆神楼 · 过街楼与乐楼",
      "清 · 顺治末至康熙初重建"
    ]
  },
  "gz_wenchang": {
    "src": "assets/plates/gz_wenchang.png",
    "alt": "贵阳文昌阁现存阁体 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "贵阳文昌阁现存阁体 · 线稿 · 待用户验收",
      "清 · 1669"
    ]
  },
  "yn_jindian": {
    "src": "assets/plates/yn_jindian.png",
    "alt": "昆明太和宫现存铜金殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "昆明太和宫现存铜金殿 · 线稿 · 待用户验收",
      "清 · 1671"
    ]
  },
  "hb_qingdongling": {
    "src": "assets/plates/hb_qingdongling.png",
    "alt": "清东陵 · 孝陵神道石牌坊 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "清东陵 · 孝陵石牌坊",
      "五间六柱十一楼正立面"
    ]
  },
  "sd_mengmiao": {
    "src": "assets/plates/sd_mengmiao.png",
    "alt": "邹城孟庙亚圣殿整殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "邹城孟庙亚圣殿整殿 · 线稿",
      "清 · 1673重建 · 后世修缮"
    ]
  },
  "daimiao": {
    "src": "assets/plates/daimiao.png",
    "alt": "泰安岱庙天贶殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "岱庙天贶殿正面 · 九间重檐庑殿",
      "宋代创建 · 现存清代重修形制"
    ]
  },
  "gugong": {
    "src": "assets/plates/gugong.png",
    "alt": "北京故宫太和殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "故宫 · 太和殿",
      "十一间面阔 · 重檐庑殿顶"
    ]
  },
  "mimi": {
    "src": "assets/plates/mimi.png",
    "alt": "繁峙秘密寺文殊殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "秘密寺 · 文殊殿正面",
      "五间硬山 · 清代遗构"
    ]
  },
  "hn_kangbaiwan": {
    "src": "assets/plates/hn_kangbaiwan.png",
    "alt": "康百万庄园 · 窑楼与内院局部 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "康百万庄园 · 窑楼与内院局部",
      "明清宅院遗构 · 依实景保留楼窑组合"
    ]
  },
  "gx_gongcheng": {
    "src": "assets/plates/gx_gongcheng.png",
    "alt": "恭城文庙大成殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "恭城文庙大成殿 · 线稿",
      "明清 · 明清"
    ]
  },
  "hu_zhanggu": {
    "src": "assets/plates/hu_zhanggu.png",
    "alt": "张谷英村明清民居屋面群局部 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "张谷英村明清民居屋面群局部 · 线稿",
      "明 · 清 · 明—清"
    ]
  },
  "yn_jingzhen": {
    "src": "assets/plates/yn_jingzhen.png",
    "alt": "景真八角亭现存戒堂 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "景真八角亭现存戒堂 · 线稿 · 待用户验收",
      "清 · 1701"
    ]
  },
  "fj_chengqi": {
    "src": "assets/plates/fj_chengqi.png",
    "alt": "永定承启楼完整外观 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "永定承启楼完整外观 · 线稿",
      "清 · 1709"
    ]
  },
  "hn_wuhou": {
    "src": "assets/plates/hn_wuhou.png",
    "alt": "南阳武侯祠 · 大拜殿檐下局部 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "南阳武侯祠 · 大拜殿檐下局部",
      "清代遗构、历代修缮 · 柱梁与门扇空间"
    ]
  },
  "sx_jiezhou_guandi": {
    "src": "assets/plates/sx_jiezhou_guandi.png",
    "alt": "解州关帝庙崇宁殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "解州关帝庙 · 崇宁殿",
      "清代 · 七间重檐大殿"
    ]
  },
  "qufukongmiao": {
    "src": "assets/plates/qufukongmiao.png",
    "alt": "曲阜孔庙大成殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "曲阜孔庙大成殿正面 · 据实景照片重绘",
      "清雍正八年（1730）重建竣工 · 九间重檐歇山顶"
    ]
  },
  "im_wuta": {
    "src": "assets/plates/im_wuta.png",
    "alt": "呼和浩特五塔寺金刚座舍利宝塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "呼和浩特五塔寺金刚座舍利宝塔 · 线稿 · 待用户验收",
      "清 · 1727—1732"
    ]
  },
  "hn_zkguandi": {
    "src": "assets/plates/hn_zkguandi.png",
    "alt": "周口关帝庙 · 山门正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "周口关帝庙 · 山门正面",
      "清雍正十三年 · 五间单檐歇山顶"
    ]
  },
  "hb_qingxiling": {
    "src": "assets/plates/hb_qingxiling.png",
    "alt": "清西陵 · 泰陵隆恩殿正立面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "清西陵 · 泰陵隆恩殿",
      "五间重檐歇山殿与完整石台基"
    ]
  },
  "feiyun": {
    "src": "assets/plates/feiyun.png",
    "alt": "万荣东岳庙飞云楼·南立面 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "东岳庙 · 飞云楼",
      "三层四滴水 · 南立面"
    ]
  },
  "hu_tianhou": {
    "src": "assets/plates/hu_tianhou.png",
    "alt": "芷江天后宫石坊完整立面 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "芷江天后宫石坊完整立面 · 线稿",
      "清 · 1748"
    ]
  },
  "hn_zhongyue": {
    "src": "assets/plates/hn_zhongyue.png",
    "alt": "嵩山中岳庙 · 峻极殿中央立面局部 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "嵩山中岳庙 · 峻极殿中央立面局部",
      "清 · 清代"
    ]
  },
  "sx_jiexiu_chenghuang": {
    "src": "assets/plates/sx_jiexiu_chenghuang.png",
    "alt": "介休城隍庙前殿倒座戏台 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "介休城隍庙 · 倒座戏台",
      "清代 · 历次修复"
    ]
  },
  "hb_bishushanzhuang": {
    "src": "assets/plates/hb_bishushanzhuang.png",
    "alt": "承德避暑山庄 · 澹泊敬诚殿正立面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "承德避暑山庄 · 澹泊敬诚殿",
      "七间单檐卷棚歇山楠木殿正面"
    ]
  },
  "im_wudang": {
    "src": "assets/plates/im_wudang.png",
    "alt": "五当召苏古沁殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "五当召苏古沁殿 · 线稿 · 待用户验收",
      "清 · 乾隆时期"
    ]
  },
  "hb_puning": {
    "src": "assets/plates/hb_puning.png",
    "alt": "普宁寺 · 大乘阁完整立面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "普宁寺大乘阁",
      "六重檐高阁及正面石台阶"
    ]
  },
  "sx_dingcun": {
    "src": "assets/plates/sx_dingcun.png",
    "alt": "丁村民居丁坤大院院内厅堂与厢房片段 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "丁村民居 · 丁坤大院院内厅堂",
      "清乾隆时期 · 庭院视角"
    ]
  },
  "quanzhouwenmiao": {
    "src": "assets/plates/quanzhouwenmiao.png",
    "alt": "泉州府文庙大成殿 · 线稿",
    "width": 1678,
    "height": 937,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "泉州府文庙 · 大成殿",
      "清乾隆二十六年 · 保留宋式重檐庑殿"
    ]
  },
  "hb_putuozongcheng": {
    "src": "assets/plates/hb_putuozongcheng.png",
    "alt": "普陀宗乘之庙 · 大红台完整正面及上部实存屋顶 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "普陀宗乘之庙大红台",
      "南侧大红台及紧邻白台的外观"
    ]
  },
  "hn_kfhuiguan": {
    "src": "assets/plates/hn_kfhuiguan.png",
    "alt": "开封山陕甘会馆 · 木牌楼正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "开封山陕甘会馆 · 木牌楼正面",
      "清 · 清代"
    ]
  },
  "sx_xinjiang_longxing": {
    "src": "assets/plates/sx_xinjiang_longxing.png",
    "alt": "新绛龙兴寺塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "新绛龙兴寺 · 龙兴宝塔",
      "清乾隆重修 · 八角十三级"
    ]
  },
  "hn_guanlin": {
    "src": "assets/plates/hn_guanlin.png",
    "alt": "洛阳关林 · 千秋鉴舞楼正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "洛阳关林 · 千秋鉴舞楼正面",
      "清乾隆五十六年 · 前歇山与后硬山组合"
    ]
  },
  "hn_shedian": {
    "src": "assets/plates/hn_shedian.png",
    "alt": "赊店山陕会馆 · 悬鉴楼戏台正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "赊店山陕会馆 · 悬鉴楼戏台正面",
      "清嘉庆至道光时期 · 三重檐楼阁"
    ]
  },
  "hb_jingjue": {
    "src": "assets/plates/hb_jingjue.png",
    "alt": "净觉寺 · 现存清代正殿正立面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "玉田净觉寺 · 香阜宫",
      "正殿与前出卷棚抱厦正面"
    ]
  },
  "gs_fuxi": {
    "src": "assets/plates/gs_fuxi.png",
    "alt": "伏羲庙仪门 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "伏羲庙仪门 · 线稿",
      "清 · 1805"
    ]
  },
  "hb_dzgongyuan": {
    "src": "assets/plates/hb_dzgongyuan.png",
    "alt": "定州贡院 · 魁阁号舍完整正立面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "魁阁号舍",
      "中央魁阁与两侧号舍七组屋顶的正面组合"
    ]
  },
  "sx_jishan_jiwang": {
    "src": "assets/plates/sx_jishan_jiwang.png",
    "alt": "稷山稷王庙献殿、钟鼓楼及后稷楼上檐 · 线稿",
    "width": 1568,
    "height": 1003,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "稷山稷王庙 · 献殿与钟鼓楼",
      "清道光重建 · 后稷楼上檐"
    ]
  },
  "xitai": {
    "src": "assets/plates/xitai.png",
    "alt": "宁海岙胡胡氏宗祠 · 戏台与勾连廊内部 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "岙胡胡氏宗祠 · 戏台与勾连廊内部",
      "柱架 · 牛腿 · 藻井"
    ]
  },
  "qiufeng": {
    "src": "assets/plates/qiufeng.png",
    "alt": "万荣后土祠秋风楼 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "后土祠 · 秋风楼正面",
      "三层楼阁 · 清代重建"
    ]
  },
  "tj_shijia": {
    "src": "assets/plates/tj_shijia.png",
    "alt": "天津杨柳青石家大院 · 内院门楼与纵深门院 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "石家大院 · 内院门楼与纵深门院",
      "清末 · 1875为宅第大规模营建起点"
    ]
  },
  "hu_yueyang": {
    "src": "assets/plates/hu_yueyang.png",
    "alt": "岳阳楼三层主体楼阁 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "岳阳楼三层主体楼阁 · 线稿",
      "清 · 1880"
    ]
  },
  "hu_nanyue": {
    "src": "assets/plates/hu_nanyue.png",
    "alt": "南岳大庙圣帝殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "南岳大庙圣帝殿 · 线稿",
      "清 · 1882 · 后世修护"
    ]
  },
  "gd_chen": {
    "src": "assets/plates/gd_chen.png",
    "alt": "陈家祠中央头门立面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "陈家祠中央头门立面 · 线稿",
      "清 · 1893"
    ]
  },
  "tj_guangdonghuiguan": {
    "src": "assets/plates/tj_guangdonghuiguan.png",
    "alt": "天津广东会馆 · 戏台与鸡笼式藻井局部 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "广东会馆 · 戏台与鸡笼式藻井局部",
      "清末 · 1907年落成"
    ]
  },
  "jl_wenmiao": {
    "src": "assets/plates/jl_wenmiao.png",
    "alt": "吉林文庙大成殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "吉林文庙 · 十一开间大成殿",
      "清末1909建成 · 后续修缮另记"
    ]
  },
  "gz_jiaxiu": {
    "src": "assets/plates/gz_jiaxiu.png",
    "alt": "贵阳甲秀楼现存楼体 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "贵阳甲秀楼现存楼体 · 线稿 · 待用户验收",
      "清 · 1909"
    ]
  },
  "gx_chengyang": {
    "src": "assets/plates/gx_chengyang.png",
    "alt": "程阳永济桥全桥与五座楼亭 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#a6b0b4",
    "tint": false,
    "caption": [
      "程阳永济桥全桥与五座楼亭 · 线稿",
      "民国 · 1924竣工"
    ]
  },
  "gd_ruishi": {
    "src": "assets/plates/gd_ruishi.png",
    "alt": "开平锦江里瑞石楼完整楼体 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#a6b0b4",
    "tint": false,
    "caption": [
      "开平锦江里瑞石楼完整楼体 · 线稿",
      "民国 · 1925"
    ]
  },
  "hlj_sofia": {
    "src": "assets/plates/hlj_sofia.png",
    "alt": "哈尔滨圣索菲亚教堂 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#a6b0b4",
    "tint": false,
    "caption": [
      "圣索菲亚教堂 · 现存1932年主体",
      "红砖墙体 · 洋葱穹顶与钟楼"
    ]
  },
  "guanque": {
    "src": "assets/plates/guanque.png",
    "alt": "永济鹳雀楼 · 2002年重建楼体 · 线稿",
    "width": 1254,
    "height": 1254,
    "color": "#a6b0b4",
    "tint": false,
    "caption": [
      "鹳雀楼正面 · 四檐三层",
      "仿唐形制 · 2002年重建"
    ]
  },
  "horyuji": {
    "src": "assets/plates/horyuji.png",
    "alt": "日本奈良法隆寺金堂单体 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c2ad78",
    "tint": false,
    "caption": [
      "法隆寺 · 金堂正面",
      "飞鸟时代 · 二重入母屋造与裳阶"
    ]
  },
  "toshodaiji": {
    "src": "assets/plates/toshodaiji.png",
    "alt": "日本奈良唐招提寺金堂单体 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#9caa76",
    "tint": false,
    "caption": [
      "唐招提寺 · 金堂正面",
      "奈良时代 · 七间寄栋造"
    ]
  },
  "byodoin": {
    "src": "assets/plates/byodoin.png",
    "alt": "日本宇治平等院凤凰堂的中堂与左右翼廊、端部楼阁完整正面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#b79aca",
    "tint": false,
    "caption": [
      "平等院 · 凤凰堂正面与两翼",
      "平安时代 · 1053年"
    ]
  },
  "todaiji": {
    "src": "assets/plates/todaiji.png",
    "alt": "日本奈良东大寺南大门单体 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#68a6ad",
    "tint": false,
    "caption": [
      "东大寺 · 南大门正面",
      "镰仓时代 · 1199—1203年重建"
    ]
  },
  "kiyomizu": {
    "src": "assets/plates/kiyomizu.png",
    "alt": "京都清水寺本堂与清水舞台 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#bd8e7b",
    "tint": false,
    "caption": [
      "清水寺 · 本堂与清水舞台",
      "南面近正视 · 江户宽永十年（1633）"
    ]
  },
  "toji": {
    "src": "assets/plates/toji.png",
    "alt": "京都东寺五重塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#bd8e7b",
    "tint": false,
    "caption": [
      "东寺 · 五重塔",
      "近正视 · 江户宽永二十一年（1644）"
    ]
  },
  "sd_guangyue": {
    "src": "assets/plates/sd_guangyue.png",
    "alt": "聊城光岳楼整楼与台基 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "光岳楼 · 整楼与台基 · 线稿",
      "四层木楼 · 明洪武七年（1374）"
    ]
  },
  "sd_yantai_huiguan": {
    "src": "assets/plates/sd_yantai_huiguan.png",
    "alt": "烟台福建会馆沿街外观 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "烟台福建会馆 · 沿街外观 · 线稿",
      "闽南会馆 · 清光绪三十二年（1906）"
    ]
  },
  "sd_jiuding": {
    "src": "assets/plates/sd_jiuding.png",
    "alt": "济南九顶塔整塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#d6ab5c",
    "tint": false,
    "caption": [
      "九顶塔 · 八角砖塔 · 线稿",
      "九座小塔 · 唐代遗塔"
    ]
  },
  "sd_hongjialou": {
    "src": "assets/plates/sd_hongjialou.png",
    "alt": "洪家楼天主教堂正立面 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "洪家楼天主教堂 · 正立面 · 线稿",
      "双尖塔 · 清光绪三十一年（1905）"
    ]
  },
  "sd_qingdao_catholic": {
    "src": "assets/plates/sd_qingdao_catholic.png",
    "alt": "青岛天主教堂西立面 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#a6b0b4",
    "tint": false,
    "caption": [
      "青岛天主教堂 · 西立面 · 线稿",
      "双钟塔 · 1934年建成"
    ]
  },
  "sd_qingdao_christ": {
    "src": "assets/plates/sd_qingdao_christ.png",
    "alt": "青岛基督教堂主堂与钟楼 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "青岛基督教堂 · 主堂与钟楼 · 线稿",
      "不对称立面 · 1910年建成"
    ]
  },
  "sd_yanmiao": {
    "src": "assets/plates/sd_yanmiao.png",
    "alt": "曲阜颜庙复圣殿整殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "曲阜颜庙 · 复圣殿 · 线稿",
      "七间重檐 · 明正德二年（1507）重建"
    ]
  },
  "sd_chongjue": {
    "src": "assets/plates/sd_chongjue.png",
    "alt": "济宁崇觉寺铁塔塔身与上部台座 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "崇觉寺铁塔 · 塔身与上部台座 · 线稿",
      "宋建七层 · 明增两层与塔刹"
    ]
  },
  "hb_shanhaiguan": {
    "src": "assets/plates/hb_shanhaiguan.png",
    "alt": "山海关镇东楼及城台 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "山海关 · 镇东楼与城台",
      "明代箭楼 · 历代及近现代修缮"
    ]
  },
  "hb_pule": {
    "src": "assets/plates/hb_pule.png",
    "alt": "普乐寺旭光阁与上层台基 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "普乐寺 · 旭光阁与上层台基",
      "双重圆檐 · 清乾隆三十一年（1766）"
    ]
  },
  "hb_anyuan": {
    "src": "assets/plates/hb_anyuan.png",
    "alt": "安远庙普度殿整殿 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "安远庙 · 普度殿",
      "三重檐方殿 · 清乾隆二十九年（1764）"
    ]
  },
  "hb_zhili": {
    "src": "assets/plates/hb_zhili.png",
    "alt": "直隶总督署大堂 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "直隶总督署 · 大堂",
      "五间正堂 · 清雍正年间"
    ]
  },
  "hb_yongtong": {
    "src": "assets/plates/hb_yongtong.png",
    "alt": "赵县永通桥整桥侧立面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "赵县 · 永通桥整桥侧立面",
      "单孔四小券 · 金明昌年间"
    ]
  },
  "hb_tiangong": {
    "src": "assets/plates/hb_tiangong.png",
    "alt": "丰润天宫寺塔整塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#c8442b",
    "tint": false,
    "caption": [
      "天宫寺塔 · 整塔",
      "八角十三层 · 辽清宁八年（1062）始建"
    ]
  },
  "hb_shien": {
    "src": "assets/plates/hb_shien.png",
    "alt": "时恩寺大殿与清代抱厦 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "时恩寺 · 大殿与卷棚抱厦",
      "明代殿体 · 清代增建抱厦"
    ]
  },
  "hb_dajingmen": {
    "src": "assets/plates/hb_dajingmen.png",
    "alt": "大境门券门与相接短墙段 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "张家口 · 大境门与短墙段",
      "清顺治元年（1644）建门"
    ]
  },
  "ah_xuguo": {
    "src": "assets/plates/ah_xuguo.png",
    "alt": "许国石坊 · 一侧正立面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "许国石坊 · 一侧正立面",
      "明 · 1584 · 四面八柱石坊"
    ]
  },
  "ah_zhenfeng": {
    "src": "assets/plates/ah_zhenfeng.png",
    "alt": "振风塔 · 七层八角塔身与底层附檐 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "振风塔 · 七层八角塔身与底层附檐",
      "明 · 隆庆年间 · 后世修缮现状"
    ]
  },
  "ah_huaxilou": {
    "src": "assets/plates/ah_huaxilou.png",
    "alt": "花戏楼 · 院内中央戏台 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "花戏楼 · 院内中央戏台",
      "清 · 1676增建 · 后世重修"
    ]
  },
  "hn_miaole": {
    "src": "assets/plates/hn_miaole.png",
    "alt": "武陟妙乐寺塔 · 十三级方形密檐砖塔 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#8f8caa",
    "tint": false,
    "caption": [
      "武陟妙乐寺塔 · 十三级密檐",
      "后周 · 955年重修"
    ]
  },
  "hn_fawang": {
    "src": "assets/plates/hn_fawang.png",
    "alt": "登封法王寺塔 · 十五重密檐与塔顶局部 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#d6ab5c",
    "tint": false,
    "caption": [
      "法王寺塔 · 十五重密檐与塔顶局部",
      "唐代 · 建塔确年未定"
    ]
  },
  "hn_songling": {
    "src": "assets/plates/hn_songling.png",
    "alt": "北宋皇陵永昭陵 · 文官石像（东列南一） · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "永昭陵 · 文官石像（东列南一）",
      "北宋 · 1063年营陵"
    ]
  },
  "hn_bixia": {
    "src": "assets/plates/hn_bixia.png",
    "alt": "浚县碧霞宫 · 正殿前部拜殿立面 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7290bd",
    "tint": false,
    "caption": [
      "碧霞宫 · 正殿前部拜殿立面",
      "明代始建 · 明清续修"
    ]
  },
  "nx_xumishan": {
    "src": "assets/plates/nx_xumishan.png",
    "alt": "须弥山第5窟 · 弥勒大佛胸膝局部 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#d6ab5c",
    "tint": false,
    "caption": [
      "须弥山第5窟 · 弥勒大佛胸膝局部",
      "唐代造像 · 依实拍保留风化"
    ]
  },
  "nx_xixialing": {
    "src": "assets/plates/nx_xixialing.png",
    "alt": "西夏陵3号陵 · 现存夯土陵塔 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c6ac85",
    "tint": false,
    "caption": [
      "西夏陵3号陵 · 现存夯土陵塔",
      "西夏遗址 · 非原貌复原"
    ]
  },
  "nx_108towers": {
    "src": "assets/plates/nx_108towers.png",
    "alt": "青铜峡一百零八塔 · 最上三行七塔局部 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#c6ac85",
    "tint": false,
    "caption": [
      "一百零八塔 · 最上三行七塔局部",
      "西夏始建说 · 后世重修现貌"
    ]
  },
  "gs_mogao": {
    "src": "assets/plates/gs_mogao.png",
    "alt": "第96窟外部九层楼 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#d6ab5c",
    "tint": false,
    "caption": [
      "第96窟外观 · 线稿",
      "现见保护楼阁 · 非唐代原构"
    ]
  },
  "gs_yulin": {
    "src": "assets/plates/gs_yulin.png",
    "alt": "榆林河谷 · 石窟入口局部 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#d6ab5c",
    "tint": false,
    "caption": [
      "河谷窟口局部 · 线稿",
      "唐代起 · 现状意写"
    ]
  },
  "gs_maijishan": {
    "src": "assets/plates/gs_maijishan.png",
    "alt": "第13窟 · 东崖大佛局部 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#90aab6",
    "tint": false,
    "caption": [
      "第13窟东崖大佛局部 · 线稿",
      "隋代 · 现状意写"
    ]
  },
  "xj_kizil": {
    "src": "assets/plates/xj_kizil.png",
    "alt": "石窟崖壁 · 入口局部 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#9c9fbd",
    "tint": false,
    "caption": [
      "崖壁入口局部 · 线稿",
      "龟兹时期洞窟群 · 现状窟口"
    ]
  },
  "xj_kumtura": {
    "src": "assets/plates/xj_kumtura.png",
    "alt": "河谷石窟 · 崖面局部 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#9c9fbd",
    "tint": false,
    "caption": [
      "河谷崖面局部 · 线稿",
      "龟兹时期洞窟群 · 现状窟口"
    ]
  },
  "sc_huangze": {
    "src": "assets/plates/sc_huangze.png",
    "alt": "摩崖五尊像局部 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#d6ab5c",
    "tint": false,
    "caption": [
      "摩崖五尊像局部 · 线稿",
      "唐代 · 现状意写"
    ]
  },
  "sc_qianfo": {
    "src": "assets/plates/sc_qianfo.png",
    "alt": "崖壁佛龛局部 · 线稿",
    "width": 1024,
    "height": 1536,
    "color": "#d6ab5c",
    "tint": false,
    "caption": [
      "崖壁佛龛局部 · 线稿",
      "唐代约略 · 现状意写"
    ]
  },
  "sc_beishan": {
    "src": "assets/plates/sc_beishan.png",
    "alt": "北山石龛 · 菩萨造像局部 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "北山石龛局部 · 线稿",
      "宋代约略 · 现状意写"
    ]
  },
  "yn_shizhong": {
    "src": "assets/plates/yn_shizhong.png",
    "alt": "南诏王像龛局部 · 线稿",
    "width": 1536,
    "height": 1024,
    "color": "#b47f71",
    "tint": false,
    "caption": [
      "南诏王像龛局部 · 线稿",
      "约9世纪 · 现状意写"
    ]
  },
  "sn_beilin": {
    "src": "assets/plates/sn_beilin.png",
    "alt": "石台孝经碑 · 线稿",
    "width": 1086,
    "height": 1448,
    "color": "#d6ab5c",
    "tint": false,
    "caption": [
      "石台孝经碑 · 线稿",
      "745 · 现状意写"
    ]
  },
  "yn_cuanbaozi": {
    "src": "assets/plates/yn_cuanbaozi.png",
    "alt": "东晋爨宝子碑 · 线稿",
    "width": 1086,
    "height": 1448,
    "color": "#bb9179",
    "tint": false,
    "caption": [
      "爨宝子碑 · 线稿",
      "405 · 现状意写"
    ]
  },
  "yn_cuanyan": {
    "src": "assets/plates/yn_cuanyan.png",
    "alt": "南朝爨龙颜碑 · 线稿",
    "width": 1086,
    "height": 1448,
    "color": "#b58d67",
    "tint": false,
    "caption": [
      "爨龙颜碑 · 线稿",
      "458 · 现状意写"
    ]
  },
  "sn_yaowang": {
    "src": "assets/plates/sn_yaowang.png",
    "alt": "摩崖石造像一龛 · 线稿",
    "width": 1086,
    "height": 1448,
    "color": "#d6ab5c",
    "tint": false,
    "caption": [
      "石造像一龛 · 线稿",
      "唐代约略 · 现状意写"
    ]
  },
  "yn_duanshi": {
    "src": "assets/plates/yn_duanshi.png",
    "alt": "大理国会盟碑 · 线稿",
    "width": 1086,
    "height": 1448,
    "color": "#7d9db8",
    "tint": false,
    "caption": [
      "段氏与三十七部会盟碑 · 线稿",
      "971 · 现状意写"
    ]
  },
  "gs_xixia_stele": {
    "src": "assets/plates/gs_xixia_stele.png",
    "alt": "西夏文与汉文碑面 · 线稿",
    "width": 1086,
    "height": 1448,
    "color": "#c6ac85",
    "tint": false,
    "caption": [
      "西夏碑碑身 · 线稿",
      "1094 · 现状意写"
    ]
  },
  "js_suzhou_song": {
    "src": "assets/plates/js_suzhou_song.png",
    "alt": "平江图碑 · 线稿",
    "width": 1086,
    "height": 1448,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "平江图碑 · 线稿",
      "1229 · 现状意写"
    ]
  },
  "hn_xizhou": {
    "src": "assets/plates/hn_xizhou.png",
    "alt": "五代盟约铜柱 · 线稿",
    "width": 1086,
    "height": 1448,
    "color": "#8f8caa",
    "tint": false,
    "caption": [
      "溪州铜柱 · 线稿",
      "940 · 现状意写"
    ]
  },
  "sc_emei_buddha": {
    "src": "assets/plates/sc_emei_buddha.png",
    "alt": "普贤菩萨骑白象铜像 · 线稿",
    "width": 1086,
    "height": 1448,
    "color": "#7aa899",
    "tint": false,
    "caption": [
      "普贤铜像 · 线稿",
      "约980 · 现状意写"
    ]
  }
};

for (const site of SITES) {
  if (PLATES[site.id]) site.image = {
    ...PLATES[site.id],
    caption: PLATES[site.id].caption || [site.caption[0].replace('立面示意', '线稿'), site.caption[1]],
  };
}
