// Convert the imagegen originals to transparent plates in the existing dynasty palette.
// Run from anywhere: node scripts/prepare-plates.mjs
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync, mkdirSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import vm from 'node:vm';

const root = fileURLToPath(new URL('../', import.meta.url));
const { SITES: sites, DYN: dynasties } = vm.runInNewContext(readFileSync(path.join(root, 'sites.js'), 'utf8') + '\n({ SITES, DYN })');
const css = readFileSync(path.join(root, 'style.css'), 'utf8');
const palette = Object.fromEntries([...css.matchAll(/(--[\w-]+):\s*(#[\da-f]{6})\s*;/gi)].map(match => [match[1], match[2]]));
const paletteUpdated = Math.max(...['sites.js', 'style.css', 'scripts/prepare-plates.mjs'].map(file => statSync(path.join(root, file)).mtimeMs));
const plates = {};
const sources = [];
mkdirSync(path.join(root, 'assets/plates'), { recursive: true });
for (const { id, dyn } of [{ id: 'hero', dyn: 'tang' }, ...sites]) {
  const original = path.join(root, `assets/generated/${id}.png`);
  const metadataFile = path.join(root, `assets/research/${id}.json`);
  if (!existsSync(original) || !existsSync(metadataFile)) {
    const existing = sites.find(site => site.id === id)?.image?.src;
    if (existing && existsSync(path.join(root, existing))) continue;
    throw new Error(`Catalogue entry ${id} needs a generated plate and research metadata before it can be added`);
  }
  const token = dynasties[dyn].acc.match(/^var\((--[\w-]+)\)$/)?.[1];
  const color = palette[token];
  if (!color) throw new Error(`Missing dynasty color for ${id} (${dyn})`);
  const target = path.join(root, `assets/plates/${id}.png`);
  if (!existsSync(target) || statSync(target).mtimeMs < Math.max(statSync(original).mtimeMs, paletteUpdated)) {
    execFileSync('magick', [original, '-background', 'white', '-alpha', 'remove', '-alpha', 'off',
      '-colorspace', 'gray', '-negate', '-level', '1%,100%', '-alpha', 'copy', '-colorspace', 'sRGB',
      '-channel', 'RGB', '-fill', color, '-colorize', '100%', '+channel', '-depth', '8', target]);
  }
  const [width, height] = execFileSync('magick', ['identify', '-format', '%w %h', target], { encoding: 'utf8' }).split(' ').map(Number);
  const metadata = JSON.parse(readFileSync(metadataFile, 'utf8'));
  plates[id] = { src: `assets/plates/${id}.png`, alt: `${metadata.subject} · 线稿`, width, height, color, tint: false };
  if (metadata.caption) {
    if (!Array.isArray(metadata.caption) || metadata.caption.length !== 2 || metadata.caption.some(part => typeof part !== 'string')) {
      throw new Error(`Caption for ${id} must contain two strings`);
    }
    plates[id].caption = metadata.caption;
  }
  sources.push(metadata);
}
const source = `/* Generated by scripts/prepare-plates.mjs; all artwork is local. */\nconst PLATES = ${JSON.stringify(plates, null, 2)};\n\nfor (const site of SITES) {\n  if (PLATES[site.id]) site.image = {\n    ...PLATES[site.id],\n    caption: PLATES[site.id].caption || [site.caption[0].replace('立面示意', '线稿'), site.caption[1]],\n  };\n}\n`;
writeFileSync(path.join(root, 'plates.js'), source);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const link = (url, label) => /^https?:\/\//.test(url || '') ? `<a href="${esc(url)}">${esc(label)}</a>` : esc(label);
const list = value => Array.isArray(value) ? value : value ? [value] : [];
const rows = sources.map(meta => {
  const refs = [...(meta.sources || list(meta.source_page).map((url, i) => ({
    source_page: url, author: Array.isArray(meta.author) ? meta.author[i] : meta.author,
    license: Array.isArray(meta.license) ? meta.license[i] : meta.license,
    license_url: Array.isArray(meta.license_url) ? meta.license_url[i] : meta.license_url,
  }))), ...list(meta.additional_sources)];
  const history = [...list(meta.historical_sources), ...list(meta.factual_sources)];
  return `<article id="${esc(meta.id)}"><a class="preview" href="proof.html?fig=${esc(meta.id)}"><img src="${esc(plates[meta.id].src)}" alt="${esc(plates[meta.id].alt)}" loading="lazy" width="${plates[meta.id].width}" height="${plates[meta.id].height}"></a><div><h2>${esc(meta.subject)}</h2><p>${esc(meta.source_note)}</p>${refs.map((ref, i) => `<p class="credit">${link(ref.source_page || ref.page, `参考图 ${i + 1}`)} · ${esc(ref.author || '作者见来源页')} · ${link(ref.license_url, ref.license || '许可见来源页')}</p>`).join('')}${history.length ? `<p class="credit">形制与年代：${history.map(ref => link(ref.url || ref.source_page, ref.title || ref.publisher || '资料来源')).join(' · ')}</p>` : ''}<p class="credit"><a href="assets/research/${esc(meta.id)}.json">参考与绘图记录</a></p></div></article>`;
}).join('\n');
writeFileSync(path.join(root, 'sources.html'), `<!DOCTYPE html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>访古 · 图版来源</title><link rel="stylesheet" href="style.css">
<style>main{max-width:1000px;margin:auto;padding:48px 24px}nav{display:flex;gap:28px;margin-bottom:48px;font-size:12px}h1{font-weight:400;font-size:36px}header p{max-width:44em;line-height:1.9;color:var(--paper-2)}article{display:grid;grid-template-columns:200px 1fr;gap:36px;align-items:center;padding:32px 0;border-top:1px solid rgba(214,171,92,.18)}article h2{font-size:22px;font-weight:400}article p{font-size:14px;line-height:1.8;color:var(--paper-2)}.preview img{width:100%;height:230px;object-fit:contain}.credit{font-size:12px!important;overflow-wrap:anywhere}a{color:var(--gold)}@media(max-width:600px){article{grid-template-columns:1fr;gap:12px}.preview img{height:260px}}</style></head><body><main>
<nav class="mono"><a href="index.html">← 访古</a><a href="proof.html?view=grid">线稿总览</a></nav><header><h1>图版来源</h1><p>以龙门石窟卢舍那大佛线稿为母版，参照下列照片与历史图像，经 AI 简化、调整视角并重绘为统一线稿。图版保留透明背景，并沿用朝代配色：汉为赭石、北魏为藕紫、南朝为暖褐、北齐为玫瑰紫、隋为青瓷、唐为金色、五代十国为灰紫、宋为铜绿、辽金为朱砂、元为琥珀、明清为青蓝、近现代为灰银。日本时代另用独立配色：飞鸟为淡赭、奈良为灰绿、平安为藤紫、镰仓为青碧、江户为茶红。<a href="assets/research/japan-periods.json">日本时代分界依据</a>。线稿为艺术意写，不作为实测或修缮依据。摄影与原图作者、许可列于各项；完整提示词和参考路径保存在绘图记录中。</p><p>卢舍那大佛沿用项目原有图版，其原始参考与许可未在项目中记录。</p></header>
${rows}
</main></body></html>\n`);
console.log(`Prepared ${Object.keys(plates).length} imagegen plates. Existing Vairocana master preserved.`);
